/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateSandboxJobInputBody,
  CreateSandboxJobOutputBody,
  ErrorModel,
  GetSandboxJobLogsOutputBody,
  GetSandboxJobLogsParams,
  ListSandboxJobsOutputBody,
  ListSandboxJobsParams,
  SandboxJob
} from '../../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type listSandboxJobsResponse200 = {
  data: ListSandboxJobsOutputBody
  status: 200
}

export type listSandboxJobsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listSandboxJobsResponseSuccess = (listSandboxJobsResponse200) & {
  headers: Headers;
};
export type listSandboxJobsResponseError = (listSandboxJobsResponseDefault) & {
  headers: Headers;
};

export type listSandboxJobsResponse = (listSandboxJobsResponseSuccess | listSandboxJobsResponseError)

export const getListSandboxJobsUrl = (organizationId: string,
    params?: ListSandboxJobsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations/${organizationId}/sandbox/jobs?${stringifiedParams}` : `/api/v1/organizations/${organizationId}/sandbox/jobs`
}

export const listSandboxJobs = async (organizationId: string,
    params?: ListSandboxJobsParams, options?: RequestInit): Promise<listSandboxJobsResponse> => {
  
  const res = await fetch(getListSandboxJobsUrl(organizationId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listSandboxJobsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listSandboxJobsResponse
}





export const getListSandboxJobsQueryKey = (organizationId: string,
    params?: ListSandboxJobsParams,) => {
    return [
    `/api/v1/organizations/${organizationId}/sandbox/jobs`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListSandboxJobsQueryOptions = <TData = Awaited<ReturnType<typeof listSandboxJobs>>, TError = ErrorModel>(organizationId: string,
    params?: ListSandboxJobsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listSandboxJobs>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSandboxJobsQueryKey(organizationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSandboxJobs>>> = ({ signal }) => listSandboxJobs(organizationId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listSandboxJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSandboxJobsQueryResult = NonNullable<Awaited<ReturnType<typeof listSandboxJobs>>>
export type ListSandboxJobsQueryError = ErrorModel



export function createListSandboxJobs<TData = Awaited<ReturnType<typeof listSandboxJobs>>, TError = ErrorModel>(
 organizationId: () =>  string,
    params?: () =>  ListSandboxJobsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listSandboxJobs>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getListSandboxJobsQueryOptions(organizationId(),
    params?.(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type createSandboxJobResponse200 = {
  data: CreateSandboxJobOutputBody
  status: 200
}

export type createSandboxJobResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createSandboxJobResponseSuccess = (createSandboxJobResponse200) & {
  headers: Headers;
};
export type createSandboxJobResponseError = (createSandboxJobResponseDefault) & {
  headers: Headers;
};

export type createSandboxJobResponse = (createSandboxJobResponseSuccess | createSandboxJobResponseError)

export const getCreateSandboxJobUrl = (organizationId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/sandbox/jobs`
}

export const createSandboxJob = async (organizationId: string,
    createSandboxJobInputBody: NonReadonly<CreateSandboxJobInputBody>, options?: RequestInit): Promise<createSandboxJobResponse> => {
  
  const res = await fetch(getCreateSandboxJobUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSandboxJobInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createSandboxJobResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSandboxJobResponse
}




export const getCreateSandboxJobMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createSandboxJob>>, TError,{organizationId: string;data: NonReadonly<CreateSandboxJobInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createSandboxJob>>, TError,{organizationId: string;data: NonReadonly<CreateSandboxJobInputBody>}, TContext> => {

const mutationKey = ['createSandboxJob'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSandboxJob>>, {organizationId: string;data: NonReadonly<CreateSandboxJobInputBody>}> = (props) => {
          const {organizationId,data} = props ?? {};

          return  createSandboxJob(organizationId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSandboxJobMutationResult = NonNullable<Awaited<ReturnType<typeof createSandboxJob>>>
    export type CreateSandboxJobMutationBody = NonReadonly<CreateSandboxJobInputBody>
    export type CreateSandboxJobMutationError = ErrorModel

    export const createCreateSandboxJob = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createSandboxJob>>, TError,{organizationId: string;data: NonReadonly<CreateSandboxJobInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createSandboxJob>>,
        TError,
        {organizationId: string;data: NonReadonly<CreateSandboxJobInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateSandboxJobMutationOptions(options?.()), queryClient }));
    }
    export type getSandboxJobResponse200 = {
  data: SandboxJob
  status: 200
}

export type getSandboxJobResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getSandboxJobResponseSuccess = (getSandboxJobResponse200) & {
  headers: Headers;
};
export type getSandboxJobResponseError = (getSandboxJobResponseDefault) & {
  headers: Headers;
};

export type getSandboxJobResponse = (getSandboxJobResponseSuccess | getSandboxJobResponseError)

export const getGetSandboxJobUrl = (organizationId: string,
    jobId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/sandbox/jobs/${jobId}`
}

export const getSandboxJob = async (organizationId: string,
    jobId: string, options?: RequestInit): Promise<getSandboxJobResponse> => {
  
  const res = await fetch(getGetSandboxJobUrl(organizationId,jobId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSandboxJobResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSandboxJobResponse
}





export const getGetSandboxJobQueryKey = (organizationId: string,
    jobId: string,) => {
    return [
    `/api/v1/organizations/${organizationId}/sandbox/jobs/${jobId}`
    ] as const;
    }

    
export const getGetSandboxJobQueryOptions = <TData = Awaited<ReturnType<typeof getSandboxJob>>, TError = ErrorModel>(organizationId: string,
    jobId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getSandboxJob>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSandboxJobQueryKey(organizationId,jobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSandboxJob>>> = ({ signal }) => getSandboxJob(organizationId,jobId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId && jobId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getSandboxJob>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSandboxJobQueryResult = NonNullable<Awaited<ReturnType<typeof getSandboxJob>>>
export type GetSandboxJobQueryError = ErrorModel



export function createGetSandboxJob<TData = Awaited<ReturnType<typeof getSandboxJob>>, TError = ErrorModel>(
 organizationId: () =>  string,
    jobId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getSandboxJob>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetSandboxJobQueryOptions(organizationId(),
    jobId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type cancelSandboxJobResponse204 = {
  data: void
  status: 204
}

export type cancelSandboxJobResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type cancelSandboxJobResponseSuccess = (cancelSandboxJobResponse204) & {
  headers: Headers;
};
export type cancelSandboxJobResponseError = (cancelSandboxJobResponseDefault) & {
  headers: Headers;
};

export type cancelSandboxJobResponse = (cancelSandboxJobResponseSuccess | cancelSandboxJobResponseError)

export const getCancelSandboxJobUrl = (organizationId: string,
    jobId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/sandbox/jobs/${jobId}/cancel`
}

export const cancelSandboxJob = async (organizationId: string,
    jobId: string, options?: RequestInit): Promise<cancelSandboxJobResponse> => {
  
  const res = await fetch(getCancelSandboxJobUrl(organizationId,jobId),
  {
      credentials: 'include',
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: cancelSandboxJobResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as cancelSandboxJobResponse
}




export const getCancelSandboxJobMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof cancelSandboxJob>>, TError,{organizationId: string;jobId: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof cancelSandboxJob>>, TError,{organizationId: string;jobId: string}, TContext> => {

const mutationKey = ['cancelSandboxJob'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cancelSandboxJob>>, {organizationId: string;jobId: string}> = (props) => {
          const {organizationId,jobId} = props ?? {};

          return  cancelSandboxJob(organizationId,jobId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CancelSandboxJobMutationResult = NonNullable<Awaited<ReturnType<typeof cancelSandboxJob>>>
    
    export type CancelSandboxJobMutationError = ErrorModel

    export const createCancelSandboxJob = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof cancelSandboxJob>>, TError,{organizationId: string;jobId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof cancelSandboxJob>>,
        TError,
        {organizationId: string;jobId: string},
        TContext
      > => {
      return createMutation(() => ({ ...getCancelSandboxJobMutationOptions(options?.()), queryClient }));
    }
    export type getSandboxJobLogsResponse200 = {
  data: GetSandboxJobLogsOutputBody
  status: 200
}

export type getSandboxJobLogsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getSandboxJobLogsResponseSuccess = (getSandboxJobLogsResponse200) & {
  headers: Headers;
};
export type getSandboxJobLogsResponseError = (getSandboxJobLogsResponseDefault) & {
  headers: Headers;
};

export type getSandboxJobLogsResponse = (getSandboxJobLogsResponseSuccess | getSandboxJobLogsResponseError)

export const getGetSandboxJobLogsUrl = (organizationId: string,
    jobId: string,
    params?: GetSandboxJobLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations/${organizationId}/sandbox/jobs/${jobId}/logs?${stringifiedParams}` : `/api/v1/organizations/${organizationId}/sandbox/jobs/${jobId}/logs`
}

export const getSandboxJobLogs = async (organizationId: string,
    jobId: string,
    params?: GetSandboxJobLogsParams, options?: RequestInit): Promise<getSandboxJobLogsResponse> => {
  
  const res = await fetch(getGetSandboxJobLogsUrl(organizationId,jobId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSandboxJobLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSandboxJobLogsResponse
}





export const getGetSandboxJobLogsQueryKey = (organizationId: string,
    jobId: string,
    params?: GetSandboxJobLogsParams,) => {
    return [
    `/api/v1/organizations/${organizationId}/sandbox/jobs/${jobId}/logs`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetSandboxJobLogsQueryOptions = <TData = Awaited<ReturnType<typeof getSandboxJobLogs>>, TError = ErrorModel>(organizationId: string,
    jobId: string,
    params?: GetSandboxJobLogsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getSandboxJobLogs>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSandboxJobLogsQueryKey(organizationId,jobId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSandboxJobLogs>>> = ({ signal }) => getSandboxJobLogs(organizationId,jobId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId && jobId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getSandboxJobLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSandboxJobLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getSandboxJobLogs>>>
export type GetSandboxJobLogsQueryError = ErrorModel



export function createGetSandboxJobLogs<TData = Awaited<ReturnType<typeof getSandboxJobLogs>>, TError = ErrorModel>(
 organizationId: () =>  string,
    jobId: () =>  string,
    params?: () =>  GetSandboxJobLogsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getSandboxJobLogs>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetSandboxJobLogsQueryOptions(organizationId(),
    jobId(),
    params?.(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




