/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateOrganizationInputBody,
  CreateOrganizationOutputBody,
  ErrorModel,
  ListOrganizationsOutputBody
} from '../../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type listOrganizationsResponse200 = {
  data: ListOrganizationsOutputBody
  status: 200
}

export type listOrganizationsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listOrganizationsResponseSuccess = (listOrganizationsResponse200) & {
  headers: Headers;
};
export type listOrganizationsResponseError = (listOrganizationsResponseDefault) & {
  headers: Headers;
};

export type listOrganizationsResponse = (listOrganizationsResponseSuccess | listOrganizationsResponseError)

export const getListOrganizationsUrl = () => {


  

  return `http://localhost:8080/api/v1/organizations`
}

export const listOrganizations = async ( options?: RequestInit): Promise<listOrganizationsResponse> => {
  
  const res = await fetch(getListOrganizationsUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listOrganizationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listOrganizationsResponse
}





export const getListOrganizationsQueryKey = () => {
    return [
    `http://localhost:8080/api/v1/organizations`
    ] as const;
    }

    
export const getListOrganizationsQueryOptions = <TData = Awaited<ReturnType<typeof listOrganizations>>, TError = ErrorModel>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listOrganizations>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListOrganizationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOrganizations>>> = ({ signal }) => listOrganizations({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listOrganizations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListOrganizationsQueryResult = NonNullable<Awaited<ReturnType<typeof listOrganizations>>>
export type ListOrganizationsQueryError = ErrorModel



export function createListOrganizations<TData = Awaited<ReturnType<typeof listOrganizations>>, TError = ErrorModel>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listOrganizations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getListOrganizationsQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type createOrganizationResponse200 = {
  data: CreateOrganizationOutputBody
  status: 200
}

export type createOrganizationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createOrganizationResponseSuccess = (createOrganizationResponse200) & {
  headers: Headers;
};
export type createOrganizationResponseError = (createOrganizationResponseDefault) & {
  headers: Headers;
};

export type createOrganizationResponse = (createOrganizationResponseSuccess | createOrganizationResponseError)

export const getCreateOrganizationUrl = () => {


  

  return `http://localhost:8080/api/v1/organizations`
}

export const createOrganization = async (createOrganizationInputBody: NonReadonly<CreateOrganizationInputBody>, options?: RequestInit): Promise<createOrganizationResponse> => {
  
  const res = await fetch(getCreateOrganizationUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrganizationInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createOrganizationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createOrganizationResponse
}




export const getCreateOrganizationMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: NonReadonly<CreateOrganizationInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: NonReadonly<CreateOrganizationInputBody>}, TContext> => {

const mutationKey = ['createOrganization'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrganization>>, {data: NonReadonly<CreateOrganizationInputBody>}> = (props) => {
          const {data} = props ?? {};

          return  createOrganization(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof createOrganization>>>
    export type CreateOrganizationMutationBody = NonReadonly<CreateOrganizationInputBody>
    export type CreateOrganizationMutationError = ErrorModel

    export const createCreateOrganization = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: NonReadonly<CreateOrganizationInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createOrganization>>,
        TError,
        {data: NonReadonly<CreateOrganizationInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateOrganizationMutationOptions(options?.()), queryClient }));
    }
    