// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (id, organization_id, key_hash, name, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, organization_id, key_hash, name, last_used_at, expires_at, created_at, revoked_at
`

type CreateApiKeyParams struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	KeyHash        string             `json:"key_hash"`
	Name           string             `json:"name"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.OrganizationID,
		arg.KeyHash,
		arg.Name,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM api_keys WHERE id = $1 AND organization_id = $2
`

type DeleteApiKeyParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error {
	_, err := q.db.Exec(ctx, deleteApiKey, arg.ID, arg.OrganizationID)
	return err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, organization_id, key_hash, name, last_used_at, expires_at, created_at, revoked_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getApiKeyByID = `-- name: GetApiKeyByID :one
SELECT id, organization_id, key_hash, name, last_used_at, expires_at, created_at, revoked_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetApiKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listApiKeysByOrganizationID = `-- name: ListApiKeysByOrganizationID :many
SELECT id, organization_id, key_hash, name, last_used_at, expires_at, created_at, revoked_at FROM api_keys
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysByOrganizationID(ctx context.Context, organizationID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.KeyHash,
			&i.Name,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1 AND organization_id = $2 AND revoked_at IS NULL
RETURNING id, organization_id, key_hash, name, last_used_at, expires_at, created_at, revoked_at
`

type RevokeApiKeyParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeApiKey, arg.ID, arg.OrganizationID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.KeyHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE key_hash = $1
`

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, keyHash string) error {
	_, err := q.db.Exec(ctx, updateApiKeyLastUsed, keyHash)
	return err
}
