// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboards.sql

package db

import (
	"context"
)

const createDashboard = `-- name: CreateDashboard :one
INSERT INTO dashboards (id, organization_id, name, description, panels, layout, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, organization_id, name, description, panels, layout, created_by, created_at, updated_at
`

type CreateDashboardParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	Panels         []byte `json:"panels"`
	Layout         []byte `json:"layout"`
	CreatedBy      string `json:"created_by"`
}

func (q *Queries) CreateDashboard(ctx context.Context, arg CreateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, createDashboard,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Panels,
		arg.Layout,
		arg.CreatedBy,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Panels,
		&i.Layout,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDashboard = `-- name: DeleteDashboard :exec
DELETE FROM dashboards WHERE id = $1 AND organization_id = $2
`

type DeleteDashboardParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteDashboard(ctx context.Context, arg DeleteDashboardParams) error {
	_, err := q.db.Exec(ctx, deleteDashboard, arg.ID, arg.OrganizationID)
	return err
}

const getDashboardByID = `-- name: GetDashboardByID :one
SELECT id, organization_id, name, description, panels, layout, created_by, created_at, updated_at FROM dashboards
WHERE id = $1 AND organization_id = $2
`

type GetDashboardByIDParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetDashboardByID(ctx context.Context, arg GetDashboardByIDParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, getDashboardByID, arg.ID, arg.OrganizationID)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Panels,
		&i.Layout,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDashboardsByOrganizationID = `-- name: ListDashboardsByOrganizationID :many
SELECT id, organization_id, name, description, panels, layout, created_by, created_at, updated_at FROM dashboards
WHERE organization_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListDashboardsByOrganizationID(ctx context.Context, organizationID string) ([]Dashboard, error) {
	rows, err := q.db.Query(ctx, listDashboardsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dashboard{}
	for rows.Next() {
		var i Dashboard
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Panels,
			&i.Layout,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDashboard = `-- name: UpdateDashboard :one
UPDATE dashboards
SET name = $3, description = $4, panels = $5, layout = $6, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, panels, layout, created_by, created_at, updated_at
`

type UpdateDashboardParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	Panels         []byte `json:"panels"`
	Layout         []byte `json:"layout"`
}

func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (Dashboard, error) {
	row := q.db.QueryRow(ctx, updateDashboard,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Panels,
		arg.Layout,
	)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Panels,
		&i.Layout,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
