// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: metric_configurations.sql

package db

import (
	"context"
)

const createMetricConfiguration = `-- name: CreateMetricConfiguration :one
INSERT INTO metric_configurations (id, organization_id, metric_name, config, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, organization_id, metric_name, config, enabled, created_at, updated_at
`

type CreateMetricConfigurationParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	MetricName     string `json:"metric_name"`
	Config         []byte `json:"config"`
	Enabled        bool   `json:"enabled"`
}

func (q *Queries) CreateMetricConfiguration(ctx context.Context, arg CreateMetricConfigurationParams) (MetricConfiguration, error) {
	row := q.db.QueryRow(ctx, createMetricConfiguration,
		arg.ID,
		arg.OrganizationID,
		arg.MetricName,
		arg.Config,
		arg.Enabled,
	)
	var i MetricConfiguration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MetricName,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMetricConfiguration = `-- name: DeleteMetricConfiguration :exec
DELETE FROM metric_configurations
WHERE organization_id = $1 AND metric_name = $2
`

type DeleteMetricConfigurationParams struct {
	OrganizationID string `json:"organization_id"`
	MetricName     string `json:"metric_name"`
}

func (q *Queries) DeleteMetricConfiguration(ctx context.Context, arg DeleteMetricConfigurationParams) error {
	_, err := q.db.Exec(ctx, deleteMetricConfiguration, arg.OrganizationID, arg.MetricName)
	return err
}

const getMetricConfiguration = `-- name: GetMetricConfiguration :one
SELECT id, organization_id, metric_name, config, enabled, created_at, updated_at FROM metric_configurations
WHERE organization_id = $1 AND metric_name = $2
`

type GetMetricConfigurationParams struct {
	OrganizationID string `json:"organization_id"`
	MetricName     string `json:"metric_name"`
}

func (q *Queries) GetMetricConfiguration(ctx context.Context, arg GetMetricConfigurationParams) (MetricConfiguration, error) {
	row := q.db.QueryRow(ctx, getMetricConfiguration, arg.OrganizationID, arg.MetricName)
	var i MetricConfiguration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MetricName,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMetricConfigurationsByOrganizationID = `-- name: ListMetricConfigurationsByOrganizationID :many
SELECT id, organization_id, metric_name, config, enabled, created_at, updated_at FROM metric_configurations
WHERE organization_id = $1
ORDER BY metric_name ASC
`

func (q *Queries) ListMetricConfigurationsByOrganizationID(ctx context.Context, organizationID string) ([]MetricConfiguration, error) {
	rows, err := q.db.Query(ctx, listMetricConfigurationsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricConfiguration{}
	for rows.Next() {
		var i MetricConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MetricName,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMetricConfiguration = `-- name: UpdateMetricConfiguration :one
UPDATE metric_configurations
SET config = $3, enabled = $4, updated_at = NOW()
WHERE organization_id = $1 AND metric_name = $2
RETURNING id, organization_id, metric_name, config, enabled, created_at, updated_at
`

type UpdateMetricConfigurationParams struct {
	OrganizationID string `json:"organization_id"`
	MetricName     string `json:"metric_name"`
	Config         []byte `json:"config"`
	Enabled        bool   `json:"enabled"`
}

func (q *Queries) UpdateMetricConfiguration(ctx context.Context, arg UpdateMetricConfigurationParams) (MetricConfiguration, error) {
	row := q.db.QueryRow(ctx, updateMetricConfiguration,
		arg.OrganizationID,
		arg.MetricName,
		arg.Config,
		arg.Enabled,
	)
	var i MetricConfiguration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MetricName,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
