// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                string             `json:"id"`
	UserID            string             `json:"user_id"`
	Provider          string             `json:"provider"`
	ProviderAccountID string             `json:"provider_account_id"`
	PasswordHash      pgtype.Text        `json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ApiKey struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	KeyHash        string             `json:"key_hash"`
	Name           string             `json:"name"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type Dashboard struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	Panels         []byte             `json:"panels"`
	Layout         []byte             `json:"layout"`
	CreatedBy      string             `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MetricConfiguration struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	MetricName     string             `json:"metric_name"`
	Config         []byte             `json:"config"`
	Enabled        bool               `json:"enabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Logo      pgtype.Text        `json:"logo"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationInvitation struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	InvitedByID    string             `json:"invited_by_id"`
	Status         string             `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID                   string             `json:"id"`
	Token                string             `json:"token"`
	UserID               string             `json:"user_id"`
	ActiveOrganizationID pgtype.Text        `json:"active_organization_id"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            string             `json:"id"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	Name          string             `json:"name"`
	Image         pgtype.Text        `json:"image"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
