/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface ApiKey {
  created_at: string;
  /** @nullable */
  expires_at: string | null;
  id: string;
  /** @nullable */
  last_used_at: string | null;
  name: string;
  organization_id: string;
  /** @nullable */
  revoked_at: string | null;
}
