/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface AutoResolveContextSummary {
  nearby_error_log_count: number;
  trace_span_count: number;
}
