/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { AutoResolveContextSummary } from './autoResolveContextSummary';

export interface AutoResolvePreview {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  base_branch: string;
  commit_message: string;
  context_summary: AutoResolveContextSummary;
  log_id: string;
  repository_full_name: string;
  repository_id: string;
  service_name: string;
  task_title: string;
  /** @nullable */
  validation_commands: string[] | null;
}
