/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface AutoResolveThreshold {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  cooldown: string;
  created_at: string;
  enabled: boolean;
  id: string;
  last_triggered_at?: string;
  lookback_window: string;
  metric_name: string;
  quorum: number;
  service_name: string;
  threshold_value: number;
  updated_at: string;
}
