/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSandboxJobInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  base_branch?: string;
  /**
   * @minItems 1
   * @nullable
   */
  commands: string[] | null;
  /** @minLength 1 */
  commit_message: string;
  draft_pr?: boolean;
  /** @minLength 1 */
  repository_id: string;
  task_title?: string;
}
