/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateRestoreJobInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** End day in YYYY-MM-DD */
  end_day: string;
  /** Signal name: logs, traces, metrics */
  signal: string;
  /** Start day in YYYY-MM-DD */
  start_day: string;
}
