/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardLayout } from './dashboardLayout';
import type { DashboardPanel } from './dashboardPanel';

export interface CreateDashboardInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  name: string;
  description?: string;
  /** @nullable */
  panels?: DashboardPanel[] | null;
  /** @nullable */
  layout?: DashboardLayout[] | null;
}
