/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateOrganizationInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  logo?: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  set_as_active_organization: boolean;
}
