/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardPanelQuery } from './dashboardPanelQuery';
import type { DashboardPanelVisualization } from './dashboardPanelVisualization';

export interface DashboardPanel {
  id: string;
  title: string;
  type: string;
  query: DashboardPanelQuery;
  visualization?: DashboardPanelVisualization;
}
