/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface DashboardLayout {
  h: number;
  panel_id: string;
  w: number;
  x: number;
  y: number;
}
