/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardLayout } from './dashboardLayout';
import type { DashboardPanel } from './dashboardPanel';

export interface Dashboard {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  created_by: string;
  description: string;
  id: string;
  /** @nullable */
  layout: DashboardLayout[] | null;
  name: string;
  organization_id: string;
  /** @nullable */
  panels: DashboardPanel[] | null;
  updated_at: string;
}
