/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardPanelQueryFilters } from './dashboardPanelQueryFilters';

export interface DashboardPanelQuery {
  metric_name: string;
  filters?: DashboardPanelQueryFilters;
  /** @nullable */
  group_by?: string[] | null;
  aggregation: string;
  step?: string;
}
