/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type GetLogHistogramParams = {
/**
 * Start time (RFC3339)
 */
start?: string;
/**
 * End time (RFC3339)
 */
end?: string;
/**
 * Bucket interval (1m, 5m, 15m, 30m, 1h, 6h, 12h, 1d)
 */
interval?: string;
/**
 * Full-text search on log body
 */
search?: string;
/**
 * Filter by service name (comma-separated)
 */
service?: string;
/**
 * Filter by severity (comma-separated)
 */
severity?: string;
};
