/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type GetMetricCatalogParams = {
/**
 * Filter by service name
 */
service?: string;
/**
 * Search on metric name
 */
search?: string;
};
