/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type GetMetricSummaryParams = {
/**
 * Metric name
 */
metric: string;
/**
 * Aggregation function (avg, sum, min, max, last, count, p50, p90, p95, p99)
 */
aggregation?: string;
/**
 * Filter by service name
 */
service?: string;
/**
 * Lookback window (e.g. 5m, 1h, 1d)
 */
lookback?: string;
/**
 * Attribute filters as key=value pairs separated by commas
 */
filters?: string;
};
