/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type GetRedMetricsParams = {
/**
 * Service name
 */
service: string;
/**
 * Start time (RFC3339)
 */
start?: string;
/**
 * End time (RFC3339)
 */
end?: string;
/**
 * Time step (1m, 5m, 15m, 30m, 1h, 6h, 12h, 1d)
 */
step?: string;
};
