/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { TimeseriesPoint } from './timeseriesPoint';

export interface GetREDMetricsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  request_rate: TimeseriesPoint[] | null;
  /** @nullable */
  error_rate: TimeseriesPoint[] | null;
  /** @nullable */
  p50_latency: TimeseriesPoint[] | null;
  /** @nullable */
  p90_latency: TimeseriesPoint[] | null;
  /** @nullable */
  p95_latency: TimeseriesPoint[] | null;
  /** @nullable */
  p99_latency: TimeseriesPoint[] | null;
}
