/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionDataOutputOrganization } from './getSessionDataOutputOrganization';
import type { Session } from './session';
import type { User } from './user';

export interface GetSessionOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  active_organization: GetSessionDataOutputOrganization;
  session: Session;
  user: User;
}
