/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface GetSessionDataOutputOrganization {
  created_at: string;
  id: string;
  /** @nullable */
  logo: string | null;
  member_role: string;
  name: string;
  updated_at: string;
}
