/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface GithubRepository {
  archived: boolean;
  created_at: string;
  default_branch: string;
  enabled: boolean;
  full_name: string;
  github_repository_id: number;
  id: string;
  installation_id: string;
  last_synced_at: string;
  organization_id: string;
  private: boolean;
  updated_at: string;
}
