/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface GithubInstallation {
  account_id: number;
  account_login: string;
  account_type: string;
  active: boolean;
  created_at: string;
  github_installation_id: number;
  id: string;
  organization_id: string;
  updated_at: string;
}
