/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface HistogramBucket {
  /** @minimum 0 */
  count: number;
  /** @minimum 0 */
  debug: number;
  /** @minimum 0 */
  error: number;
  /** @minimum 0 */
  fatal: number;
  /** @minimum 0 */
  info: number;
  time: string;
  /** @minimum 0 */
  warn: number;
}
