/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { AutoResolveThreshold } from './autoResolveThreshold';

export interface ListAutoResolveThresholdsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  thresholds: AutoResolveThreshold[] | null;
}
