/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type ListSandboxJobsParams = {
/**
 * Comma-separated job states to include (e.g. queued,running)
 */
state?: string;
/**
 * Max jobs to return (default 20, max 200)
 */
limit?: number;
};
