/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { GithubInstallation } from './githubInstallation';

export interface ListGithubInstallationsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  installations: GithubInstallation[] | null;
}
