/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { LogRecordLogAttributes } from './logRecordLogAttributes';
import type { LogRecordResourceAttributes } from './logRecordResourceAttributes';
import type { LogRecordScopeAttributes } from './logRecordScopeAttributes';

export interface LogRecord {
  body: string;
  deployment_environment: string;
  id: string;
  log_attributes: LogRecordLogAttributes;
  observed_timestamp: string;
  organization_id: string;
  resource_attributes: LogRecordResourceAttributes;
  resource_schema_url: string;
  scope_attributes: LogRecordScopeAttributes;
  scope_name: string;
  scope_schema_url: string;
  scope_version: string;
  service_name: string;
  /** @minimum 0 */
  severity_number: number;
  severity_text: string;
  span_id: string;
  timestamp: string;
  /** @minimum 0 */
  trace_flags: number;
  trace_id: string;
}
