/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface MetricMeta {
  name: string;
  type: string;
  unit: string;
  description: string;
  service_name: string;
}
