/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface Organization {
  created_at: string;
  id: string;
  /** @nullable */
  logo: string | null;
  name: string;
  role: string;
  slug: string;
}
