/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type QueryTracesParams = {
/**
 * Start time (RFC3339)
 */
start?: string;
/**
 * End time (RFC3339)
 */
end?: string;
/**
 * Max results to return (default 50, max 500)
 */
limit?: number;
/**
 * Pagination cursor (RFC3339Nano timestamp)
 */
cursor?: string;
/**
 * Search on span name
 */
search?: string;
/**
 * Filter by service name (comma-separated)
 */
service?: string;
/**
 * Filter by status code (comma-separated: ok,error,unset)
 */
status?: string;
/**
 * Minimum trace duration in milliseconds
 */
min_duration?: number;
/**
 * Maximum trace duration in milliseconds
 */
max_duration?: number;
};
