/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { LogRecord } from './logRecord';

export interface QueryLogsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  logs: LogRecord[] | null;
  next_cursor?: string;
}
