/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type QueryLogsParams = {
/**
 * Start time (RFC3339)
 */
start?: string;
/**
 * End time (RFC3339)
 */
end?: string;
/**
 * Max results to return (default 100, max 1000)
 */
limit?: number;
/**
 * Pagination cursor (RFC3339Nano timestamp)
 */
cursor?: string;
/**
 * Full-text search on log body
 */
search?: string;
/**
 * Filter by service name (comma-separated)
 */
service?: string;
/**
 * Filter by severity (comma-separated: debug,info,warn,error,fatal)
 */
severity?: string;
};
