/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type QueryTimeseriesParams = {
/**
 * Metric name to query
 */
metric: string;
/**
 * Start time (RFC3339)
 */
start?: string;
/**
 * End time (RFC3339)
 */
end?: string;
/**
 * Time step (1m, 5m, 15m, 30m, 1h, 6h, 12h, 1d)
 */
step?: string;
/**
 * Aggregation function (avg, sum, min, max, rate, count, last, p50, p90, p95, p99)
 */
aggregation?: string;
/**
 * Filter by service name
 */
service?: string;
/**
 * Comma-separated attribute keys to group by
 */
group_by?: string;
/**
 * Attribute filters as key=value pairs separated by commas (e.g. span.name=GET /api,span.kind=2)
 */
filters?: string;
};
