/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { TraceSummary } from './traceSummary';

export interface QueryTracesOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  next_cursor?: string;
  /** @nullable */
  traces: TraceSummary[] | null;
}
