/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface RecalculateDerivedMetricsOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  as_of: string;
  combined_error_events: number;
  error_log_count: number;
  error_span_count: number;
  organization_id: string;
  request_span_count: number;
  service_name?: string;
  window_end: string;
  window_start: string;
}
