/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export type RecalculateDerivedMetricsParams = {
/**
 * Filter by service name
 */
service?: string;
/**
 * Lookback window to recalculate (e.g. 15m, 1h, 24h). Defaults to 1h.
 */
lookback?: string;
};
