/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  email: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * @minLength 8
   * @maxLength 72
   */
  password: string;
}
