/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface RestoreJobItem {
  day: string;
  error?: string;
  finished_at?: string;
  id: string;
  object_key: string;
  object_size_bytes: number;
  restored_rows: number;
  started_at?: string;
  state: string;
}
