/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { RestoreJobItem } from './restoreJobItem';

export interface RestoreJob {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  completed_items: number;
  created_at: string;
  done_bytes: number;
  end_day: string;
  error?: string;
  estimated_seconds: number;
  finished_at?: string;
  id: string;
  /** @nullable */
  items?: RestoreJobItem[] | null;
  organization_id: string;
  requested_by?: string;
  signal: string;
  start_day: string;
  started_at?: string;
  state: string;
  total_bytes: number;
  total_items: number;
}
