/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface SandboxJob {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  base_branch: string;
  branch_name: string;
  cancel_requested: boolean;
  commit_message: string;
  created_at: string;
  draft_pr: boolean;
  error?: string;
  finished_at?: string;
  id: string;
  mode: string;
  organization_id: string;
  /** @nullable */
  pull_request_number: number | null;
  /** @nullable */
  pull_request_url: string | null;
  repository_id: string;
  requested_by_user_id: string;
  runtime_type: string;
  sandbox_instance_id: string;
  started_at?: string;
  state: string;
  task_title: string;
  updated_at: string;
}
