/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceEdge {
  avg_duration_ns: number;
  /** @minimum 0 */
  error_count: number;
  /** @minimum 0 */
  request_count: number;
  source: string;
  target: string;
}
