/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface ServiceSource {
  avg_duration_ns: number;
  /** @minimum 0 */
  error_count: number;
  last_seen: string;
  service_name: string;
  /** @minimum 0 */
  span_count: number;
}
