/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface Session {
  /** @nullable */
  active_organization_id: string | null;
  created_at: string;
  expires_at: string;
  id: string;
  /** @nullable */
  ip_address: string | null;
  updated_at: string;
  /** @nullable */
  user_agent: string | null;
  user_id: string;
}
