/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { SpanEventAttributes } from './spanEventAttributes';

export interface SpanEvent {
  attributes: SpanEventAttributes;
  name: string;
  timestamp: string;
}
