/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { SpanLinkAttributes } from './spanLinkAttributes';

export interface SpanLink {
  attributes: SpanLinkAttributes;
  span_id: string;
  trace_id: string;
  trace_state: string;
}
