/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { SpanEvent } from './spanEvent';
import type { SpanLink } from './spanLink';
import type { SpanResourceAttributes } from './spanResourceAttributes';
import type { SpanScopeAttributes } from './spanScopeAttributes';
import type { SpanSpanAttributes } from './spanSpanAttributes';

export interface Span {
  deployment_environment: string;
  duration_ns: number;
  end_time: string;
  /** @nullable */
  events: SpanEvent[] | null;
  id: string;
  /** @minimum 0 */
  kind: number;
  /** @nullable */
  links: SpanLink[] | null;
  name: string;
  organization_id: string;
  parent_span_id: string;
  resource_attributes: SpanResourceAttributes;
  resource_schema_url: string;
  scope_attributes: SpanScopeAttributes;
  scope_name: string;
  scope_schema_url: string;
  scope_version: string;
  service_name: string;
  span_attributes: SpanSpanAttributes;
  span_id: string;
  start_time: string;
  /** @minimum 0 */
  status_code: number;
  status_message: string;
  trace_id: string;
  trace_state: string;
}
