/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { TimeseriesLabels } from './timeseriesLabels';
import type { TimeseriesPoint } from './timeseriesPoint';

export interface Timeseries {
  labels: TimeseriesLabels;
  /** @nullable */
  points: TimeseriesPoint[] | null;
}
