/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface TraceSummary {
  duration_ns: number;
  /** @minimum 0 */
  error_count: number;
  root_service: string;
  root_span_name: string;
  /** @minimum 0 */
  span_count: number;
  start_time: string;
  trace_id: string;
}
