/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardLayout } from './dashboardLayout';
import type { DashboardPanel } from './dashboardPanel';

export interface UpdateDashboardInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Dashboard description */
  description?: string;
  /**
   * Panel layout positions
   * @nullable
   */
  layout?: DashboardLayout[] | null;
  /** Dashboard name */
  name: string;
  /**
   * Dashboard panels
   * @nullable
   */
  panels?: DashboardPanel[] | null;
}
