/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface UpsertAutoResolveThresholdInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  cooldown: string;
  enabled: boolean;
  lookback_window: string;
  quorum: number;
  threshold_value: number;
}
