/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  created_at: string;
  email: string;
  email_verified: boolean;
  id: string;
  /** @nullable */
  image: string | null;
  name: string;
  updated_at: string;
}
