/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  ErrorModel,
  GetHistogramOutputBody,
  GetLogHistogramParams,
  GetServicesOutputBody,
  QueryLogsOutputBody,
  QueryLogsParams
} from '../../model';





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type queryLogsResponse200 = {
  data: QueryLogsOutputBody
  status: 200
}

export type queryLogsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type queryLogsResponseSuccess = (queryLogsResponse200) & {
  headers: Headers;
};
export type queryLogsResponseError = (queryLogsResponseDefault) & {
  headers: Headers;
};

export type queryLogsResponse = (queryLogsResponseSuccess | queryLogsResponseError)

export const getQueryLogsUrl = (organizationId: string,
    params?: QueryLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations/${organizationId}/logs?${stringifiedParams}` : `/api/v1/organizations/${organizationId}/logs`
}

export const queryLogs = async (organizationId: string,
    params?: QueryLogsParams, options?: RequestInit): Promise<queryLogsResponse> => {
  
  const res = await fetch(getQueryLogsUrl(organizationId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: queryLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as queryLogsResponse
}





export const getQueryLogsQueryKey = (organizationId: string,
    params?: QueryLogsParams,) => {
    return [
    `/api/v1/organizations/${organizationId}/logs`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getQueryLogsQueryOptions = <TData = Awaited<ReturnType<typeof queryLogs>>, TError = ErrorModel>(organizationId: string,
    params?: QueryLogsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof queryLogs>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getQueryLogsQueryKey(organizationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof queryLogs>>> = ({ signal }) => queryLogs(organizationId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof queryLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type QueryLogsQueryResult = NonNullable<Awaited<ReturnType<typeof queryLogs>>>
export type QueryLogsQueryError = ErrorModel



export function createQueryLogs<TData = Awaited<ReturnType<typeof queryLogs>>, TError = ErrorModel>(
 organizationId: () =>  string,
    params?: () =>  QueryLogsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof queryLogs>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getQueryLogsQueryOptions(organizationId(),
    params?.(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type getLogHistogramResponse200 = {
  data: GetHistogramOutputBody
  status: 200
}

export type getLogHistogramResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getLogHistogramResponseSuccess = (getLogHistogramResponse200) & {
  headers: Headers;
};
export type getLogHistogramResponseError = (getLogHistogramResponseDefault) & {
  headers: Headers;
};

export type getLogHistogramResponse = (getLogHistogramResponseSuccess | getLogHistogramResponseError)

export const getGetLogHistogramUrl = (organizationId: string,
    params?: GetLogHistogramParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations/${organizationId}/logs/histogram?${stringifiedParams}` : `/api/v1/organizations/${organizationId}/logs/histogram`
}

export const getLogHistogram = async (organizationId: string,
    params?: GetLogHistogramParams, options?: RequestInit): Promise<getLogHistogramResponse> => {
  
  const res = await fetch(getGetLogHistogramUrl(organizationId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getLogHistogramResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getLogHistogramResponse
}





export const getGetLogHistogramQueryKey = (organizationId: string,
    params?: GetLogHistogramParams,) => {
    return [
    `/api/v1/organizations/${organizationId}/logs/histogram`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetLogHistogramQueryOptions = <TData = Awaited<ReturnType<typeof getLogHistogram>>, TError = ErrorModel>(organizationId: string,
    params?: GetLogHistogramParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getLogHistogram>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLogHistogramQueryKey(organizationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLogHistogram>>> = ({ signal }) => getLogHistogram(organizationId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getLogHistogram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLogHistogramQueryResult = NonNullable<Awaited<ReturnType<typeof getLogHistogram>>>
export type GetLogHistogramQueryError = ErrorModel



export function createGetLogHistogram<TData = Awaited<ReturnType<typeof getLogHistogram>>, TError = ErrorModel>(
 organizationId: () =>  string,
    params?: () =>  GetLogHistogramParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getLogHistogram>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetLogHistogramQueryOptions(organizationId(),
    params?.(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type getLogServicesResponse200 = {
  data: GetServicesOutputBody
  status: 200
}

export type getLogServicesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getLogServicesResponseSuccess = (getLogServicesResponse200) & {
  headers: Headers;
};
export type getLogServicesResponseError = (getLogServicesResponseDefault) & {
  headers: Headers;
};

export type getLogServicesResponse = (getLogServicesResponseSuccess | getLogServicesResponseError)

export const getGetLogServicesUrl = (organizationId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/logs/services`
}

export const getLogServices = async (organizationId: string, options?: RequestInit): Promise<getLogServicesResponse> => {
  
  const res = await fetch(getGetLogServicesUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getLogServicesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getLogServicesResponse
}





export const getGetLogServicesQueryKey = (organizationId: string,) => {
    return [
    `/api/v1/organizations/${organizationId}/logs/services`
    ] as const;
    }

    
export const getGetLogServicesQueryOptions = <TData = Awaited<ReturnType<typeof getLogServices>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getLogServices>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLogServicesQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLogServices>>> = ({ signal }) => getLogServices(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getLogServices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLogServicesQueryResult = NonNullable<Awaited<ReturnType<typeof getLogServices>>>
export type GetLogServicesQueryError = ErrorModel



export function createGetLogServices<TData = Awaited<ReturnType<typeof getLogServices>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getLogServices>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetLogServicesQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




