/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateDashboardInputBody,
  Dashboard,
  Empty,
  ErrorModel,
  ListDashboardsOutputBody,
  UpdateDashboardInputBody
} from '../../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type listDashboardsResponse200 = {
  data: ListDashboardsOutputBody
  status: 200
}

export type listDashboardsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listDashboardsResponseSuccess = (listDashboardsResponse200) & {
  headers: Headers;
};
export type listDashboardsResponseError = (listDashboardsResponseDefault) & {
  headers: Headers;
};

export type listDashboardsResponse = (listDashboardsResponseSuccess | listDashboardsResponseError)

export const getListDashboardsUrl = (organizationId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/dashboards`
}

export const listDashboards = async (organizationId: string, options?: RequestInit): Promise<listDashboardsResponse> => {
  
  const res = await fetch(getListDashboardsUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listDashboardsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listDashboardsResponse
}





export const getListDashboardsQueryKey = (organizationId: string,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/dashboards`
    ] as const;
    }

    
export const getListDashboardsQueryOptions = <TData = Awaited<ReturnType<typeof listDashboards>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listDashboards>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDashboardsQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDashboards>>> = ({ signal }) => listDashboards(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listDashboards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDashboardsQueryResult = NonNullable<Awaited<ReturnType<typeof listDashboards>>>
export type ListDashboardsQueryError = ErrorModel



export function createListDashboards<TData = Awaited<ReturnType<typeof listDashboards>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listDashboards>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getListDashboardsQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type createDashboardResponse200 = {
  data: Dashboard
  status: 200
}

export type createDashboardResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createDashboardResponseSuccess = (createDashboardResponse200) & {
  headers: Headers;
};
export type createDashboardResponseError = (createDashboardResponseDefault) & {
  headers: Headers;
};

export type createDashboardResponse = (createDashboardResponseSuccess | createDashboardResponseError)

export const getCreateDashboardUrl = (organizationId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/dashboards`
}

export const createDashboard = async (organizationId: string,
    createDashboardInputBody: NonReadonly<CreateDashboardInputBody>, options?: RequestInit): Promise<createDashboardResponse> => {
  
  const res = await fetch(getCreateDashboardUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createDashboardInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createDashboardResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createDashboardResponse
}




export const getCreateDashboardMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createDashboard>>, TError,{organizationId: string;data: NonReadonly<CreateDashboardInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createDashboard>>, TError,{organizationId: string;data: NonReadonly<CreateDashboardInputBody>}, TContext> => {

const mutationKey = ['createDashboard'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDashboard>>, {organizationId: string;data: NonReadonly<CreateDashboardInputBody>}> = (props) => {
          const {organizationId,data} = props ?? {};

          return  createDashboard(organizationId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDashboardMutationResult = NonNullable<Awaited<ReturnType<typeof createDashboard>>>
    export type CreateDashboardMutationBody = NonReadonly<CreateDashboardInputBody>
    export type CreateDashboardMutationError = ErrorModel

    export const createCreateDashboard = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createDashboard>>, TError,{organizationId: string;data: NonReadonly<CreateDashboardInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createDashboard>>,
        TError,
        {organizationId: string;data: NonReadonly<CreateDashboardInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateDashboardMutationOptions(options?.()), queryClient }));
    }
    export type deleteDashboardResponse200 = {
  data: Empty
  status: 200
}

export type deleteDashboardResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type deleteDashboardResponseSuccess = (deleteDashboardResponse200) & {
  headers: Headers;
};
export type deleteDashboardResponseError = (deleteDashboardResponseDefault) & {
  headers: Headers;
};

export type deleteDashboardResponse = (deleteDashboardResponseSuccess | deleteDashboardResponseError)

export const getDeleteDashboardUrl = (organizationId: string,
    dashboardId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/dashboards/${dashboardId}`
}

export const deleteDashboard = async (organizationId: string,
    dashboardId: string, options?: RequestInit): Promise<deleteDashboardResponse> => {
  
  const res = await fetch(getDeleteDashboardUrl(organizationId,dashboardId),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteDashboardResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteDashboardResponse
}




export const getDeleteDashboardMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteDashboard>>, TError,{organizationId: string;dashboardId: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteDashboard>>, TError,{organizationId: string;dashboardId: string}, TContext> => {

const mutationKey = ['deleteDashboard'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDashboard>>, {organizationId: string;dashboardId: string}> = (props) => {
          const {organizationId,dashboardId} = props ?? {};

          return  deleteDashboard(organizationId,dashboardId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDashboardMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDashboard>>>
    
    export type DeleteDashboardMutationError = ErrorModel

    export const createDeleteDashboard = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteDashboard>>, TError,{organizationId: string;dashboardId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteDashboard>>,
        TError,
        {organizationId: string;dashboardId: string},
        TContext
      > => {
      return createMutation(() => ({ ...getDeleteDashboardMutationOptions(options?.()), queryClient }));
    }
    export type getDashboardResponse200 = {
  data: Dashboard
  status: 200
}

export type getDashboardResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getDashboardResponseSuccess = (getDashboardResponse200) & {
  headers: Headers;
};
export type getDashboardResponseError = (getDashboardResponseDefault) & {
  headers: Headers;
};

export type getDashboardResponse = (getDashboardResponseSuccess | getDashboardResponseError)

export const getGetDashboardUrl = (organizationId: string,
    dashboardId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/dashboards/${dashboardId}`
}

export const getDashboard = async (organizationId: string,
    dashboardId: string, options?: RequestInit): Promise<getDashboardResponse> => {
  
  const res = await fetch(getGetDashboardUrl(organizationId,dashboardId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getDashboardResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDashboardResponse
}





export const getGetDashboardQueryKey = (organizationId: string,
    dashboardId: string,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/dashboards/${dashboardId}`
    ] as const;
    }

    
export const getGetDashboardQueryOptions = <TData = Awaited<ReturnType<typeof getDashboard>>, TError = ErrorModel>(organizationId: string,
    dashboardId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardQueryKey(organizationId,dashboardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboard>>> = ({ signal }) => getDashboard(organizationId,dashboardId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId && dashboardId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboard>>>
export type GetDashboardQueryError = ErrorModel



export function createGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = ErrorModel>(
 organizationId: () =>  string,
    dashboardId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetDashboardQueryOptions(organizationId(),
    dashboardId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type updateDashboardResponse200 = {
  data: Dashboard
  status: 200
}

export type updateDashboardResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type updateDashboardResponseSuccess = (updateDashboardResponse200) & {
  headers: Headers;
};
export type updateDashboardResponseError = (updateDashboardResponseDefault) & {
  headers: Headers;
};

export type updateDashboardResponse = (updateDashboardResponseSuccess | updateDashboardResponseError)

export const getUpdateDashboardUrl = (organizationId: string,
    dashboardId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/dashboards/${dashboardId}`
}

export const updateDashboard = async (organizationId: string,
    dashboardId: string,
    updateDashboardInputBody: NonReadonly<UpdateDashboardInputBody>, options?: RequestInit): Promise<updateDashboardResponse> => {
  
  const res = await fetch(getUpdateDashboardUrl(organizationId,dashboardId),
  {
      credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateDashboardInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateDashboardResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateDashboardResponse
}




export const getUpdateDashboardMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateDashboard>>, TError,{organizationId: string;dashboardId: string;data: NonReadonly<UpdateDashboardInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof updateDashboard>>, TError,{organizationId: string;dashboardId: string;data: NonReadonly<UpdateDashboardInputBody>}, TContext> => {

const mutationKey = ['updateDashboard'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDashboard>>, {organizationId: string;dashboardId: string;data: NonReadonly<UpdateDashboardInputBody>}> = (props) => {
          const {organizationId,dashboardId,data} = props ?? {};

          return  updateDashboard(organizationId,dashboardId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDashboardMutationResult = NonNullable<Awaited<ReturnType<typeof updateDashboard>>>
    export type UpdateDashboardMutationBody = NonReadonly<UpdateDashboardInputBody>
    export type UpdateDashboardMutationError = ErrorModel

    export const createUpdateDashboard = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof updateDashboard>>, TError,{organizationId: string;dashboardId: string;data: NonReadonly<UpdateDashboardInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof updateDashboard>>,
        TError,
        {organizationId: string;dashboardId: string;data: NonReadonly<UpdateDashboardInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getUpdateDashboardMutationOptions(options?.()), queryClient }));
    }
    