/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateRestoreJobInputBody,
  ErrorModel,
  RestoreJob
} from '../../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type createRestoreJobResponse200 = {
  data: RestoreJob
  status: 200
}

export type createRestoreJobResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createRestoreJobResponseSuccess = (createRestoreJobResponse200) & {
  headers: Headers;
};
export type createRestoreJobResponseError = (createRestoreJobResponseDefault) & {
  headers: Headers;
};

export type createRestoreJobResponse = (createRestoreJobResponseSuccess | createRestoreJobResponseError)

export const getCreateRestoreJobUrl = (organizationId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/archive/restores`
}

export const createRestoreJob = async (organizationId: string,
    createRestoreJobInputBody: NonReadonly<CreateRestoreJobInputBody>, options?: RequestInit): Promise<createRestoreJobResponse> => {
  
  const res = await fetch(getCreateRestoreJobUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createRestoreJobInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createRestoreJobResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRestoreJobResponse
}




export const getCreateRestoreJobMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createRestoreJob>>, TError,{organizationId: string;data: NonReadonly<CreateRestoreJobInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createRestoreJob>>, TError,{organizationId: string;data: NonReadonly<CreateRestoreJobInputBody>}, TContext> => {

const mutationKey = ['createRestoreJob'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRestoreJob>>, {organizationId: string;data: NonReadonly<CreateRestoreJobInputBody>}> = (props) => {
          const {organizationId,data} = props ?? {};

          return  createRestoreJob(organizationId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRestoreJobMutationResult = NonNullable<Awaited<ReturnType<typeof createRestoreJob>>>
    export type CreateRestoreJobMutationBody = NonReadonly<CreateRestoreJobInputBody>
    export type CreateRestoreJobMutationError = ErrorModel

    export const createCreateRestoreJob = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createRestoreJob>>, TError,{organizationId: string;data: NonReadonly<CreateRestoreJobInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createRestoreJob>>,
        TError,
        {organizationId: string;data: NonReadonly<CreateRestoreJobInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateRestoreJobMutationOptions(options?.()), queryClient }));
    }
    export type getRestoreJobResponse200 = {
  data: RestoreJob
  status: 200
}

export type getRestoreJobResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getRestoreJobResponseSuccess = (getRestoreJobResponse200) & {
  headers: Headers;
};
export type getRestoreJobResponseError = (getRestoreJobResponseDefault) & {
  headers: Headers;
};

export type getRestoreJobResponse = (getRestoreJobResponseSuccess | getRestoreJobResponseError)

export const getGetRestoreJobUrl = (organizationId: string,
    restoreJobId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/archive/restores/${restoreJobId}`
}

export const getRestoreJob = async (organizationId: string,
    restoreJobId: string, options?: RequestInit): Promise<getRestoreJobResponse> => {
  
  const res = await fetch(getGetRestoreJobUrl(organizationId,restoreJobId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getRestoreJobResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRestoreJobResponse
}





export const getGetRestoreJobQueryKey = (organizationId: string,
    restoreJobId: string,) => {
    return [
    `/api/v1/organizations/${organizationId}/archive/restores/${restoreJobId}`
    ] as const;
    }

    
export const getGetRestoreJobQueryOptions = <TData = Awaited<ReturnType<typeof getRestoreJob>>, TError = ErrorModel>(organizationId: string,
    restoreJobId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getRestoreJob>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRestoreJobQueryKey(organizationId,restoreJobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRestoreJob>>> = ({ signal }) => getRestoreJob(organizationId,restoreJobId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId && restoreJobId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getRestoreJob>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRestoreJobQueryResult = NonNullable<Awaited<ReturnType<typeof getRestoreJob>>>
export type GetRestoreJobQueryError = ErrorModel



export function createGetRestoreJob<TData = Awaited<ReturnType<typeof getRestoreJob>>, TError = ErrorModel>(
 organizationId: () =>  string,
    restoreJobId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getRestoreJob>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetRestoreJobQueryOptions(organizationId(),
    restoreJobId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




