/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  ErrorModel,
  GetServiceMapOutputBody,
  GetSourcesOutputBody,
  GetTraceOutputBody,
  GetTraceServicesOutputBody,
  QueryTracesOutputBody,
  QueryTracesParams
} from '../../model';





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type queryTracesResponse200 = {
  data: QueryTracesOutputBody
  status: 200
}

export type queryTracesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type queryTracesResponseSuccess = (queryTracesResponse200) & {
  headers: Headers;
};
export type queryTracesResponseError = (queryTracesResponseDefault) & {
  headers: Headers;
};

export type queryTracesResponse = (queryTracesResponseSuccess | queryTracesResponseError)

export const getQueryTracesUrl = (organizationId: string,
    params?: QueryTracesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/v1/organizations/${organizationId}/traces?${stringifiedParams}` : `http://localhost:8080/api/v1/organizations/${organizationId}/traces`
}

export const queryTraces = async (organizationId: string,
    params?: QueryTracesParams, options?: RequestInit): Promise<queryTracesResponse> => {
  
  const res = await fetch(getQueryTracesUrl(organizationId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: queryTracesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as queryTracesResponse
}





export const getQueryTracesQueryKey = (organizationId: string,
    params?: QueryTracesParams,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/traces`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getQueryTracesQueryOptions = <TData = Awaited<ReturnType<typeof queryTraces>>, TError = ErrorModel>(organizationId: string,
    params?: QueryTracesParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof queryTraces>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getQueryTracesQueryKey(organizationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof queryTraces>>> = ({ signal }) => queryTraces(organizationId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof queryTraces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type QueryTracesQueryResult = NonNullable<Awaited<ReturnType<typeof queryTraces>>>
export type QueryTracesQueryError = ErrorModel



export function createQueryTraces<TData = Awaited<ReturnType<typeof queryTraces>>, TError = ErrorModel>(
 organizationId: () =>  string,
    params?: () =>  QueryTracesParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof queryTraces>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getQueryTracesQueryOptions(organizationId(),
    params?.(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type getServiceMapResponse200 = {
  data: GetServiceMapOutputBody
  status: 200
}

export type getServiceMapResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getServiceMapResponseSuccess = (getServiceMapResponse200) & {
  headers: Headers;
};
export type getServiceMapResponseError = (getServiceMapResponseDefault) & {
  headers: Headers;
};

export type getServiceMapResponse = (getServiceMapResponseSuccess | getServiceMapResponseError)

export const getGetServiceMapUrl = (organizationId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/traces/service-map`
}

export const getServiceMap = async (organizationId: string, options?: RequestInit): Promise<getServiceMapResponse> => {
  
  const res = await fetch(getGetServiceMapUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getServiceMapResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getServiceMapResponse
}





export const getGetServiceMapQueryKey = (organizationId: string,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/traces/service-map`
    ] as const;
    }

    
export const getGetServiceMapQueryOptions = <TData = Awaited<ReturnType<typeof getServiceMap>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getServiceMap>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceMapQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceMap>>> = ({ signal }) => getServiceMap(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getServiceMap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetServiceMapQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceMap>>>
export type GetServiceMapQueryError = ErrorModel



export function createGetServiceMap<TData = Awaited<ReturnType<typeof getServiceMap>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getServiceMap>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetServiceMapQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type getTraceServicesResponse200 = {
  data: GetTraceServicesOutputBody
  status: 200
}

export type getTraceServicesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getTraceServicesResponseSuccess = (getTraceServicesResponse200) & {
  headers: Headers;
};
export type getTraceServicesResponseError = (getTraceServicesResponseDefault) & {
  headers: Headers;
};

export type getTraceServicesResponse = (getTraceServicesResponseSuccess | getTraceServicesResponseError)

export const getGetTraceServicesUrl = (organizationId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/traces/services`
}

export const getTraceServices = async (organizationId: string, options?: RequestInit): Promise<getTraceServicesResponse> => {
  
  const res = await fetch(getGetTraceServicesUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTraceServicesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTraceServicesResponse
}





export const getGetTraceServicesQueryKey = (organizationId: string,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/traces/services`
    ] as const;
    }

    
export const getGetTraceServicesQueryOptions = <TData = Awaited<ReturnType<typeof getTraceServices>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTraceServices>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTraceServicesQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTraceServices>>> = ({ signal }) => getTraceServices(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getTraceServices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTraceServicesQueryResult = NonNullable<Awaited<ReturnType<typeof getTraceServices>>>
export type GetTraceServicesQueryError = ErrorModel



export function createGetTraceServices<TData = Awaited<ReturnType<typeof getTraceServices>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTraceServices>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetTraceServicesQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type getTraceSourcesResponse200 = {
  data: GetSourcesOutputBody
  status: 200
}

export type getTraceSourcesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getTraceSourcesResponseSuccess = (getTraceSourcesResponse200) & {
  headers: Headers;
};
export type getTraceSourcesResponseError = (getTraceSourcesResponseDefault) & {
  headers: Headers;
};

export type getTraceSourcesResponse = (getTraceSourcesResponseSuccess | getTraceSourcesResponseError)

export const getGetTraceSourcesUrl = (organizationId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/traces/sources`
}

export const getTraceSources = async (organizationId: string, options?: RequestInit): Promise<getTraceSourcesResponse> => {
  
  const res = await fetch(getGetTraceSourcesUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTraceSourcesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTraceSourcesResponse
}





export const getGetTraceSourcesQueryKey = (organizationId: string,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/traces/sources`
    ] as const;
    }

    
export const getGetTraceSourcesQueryOptions = <TData = Awaited<ReturnType<typeof getTraceSources>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTraceSources>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTraceSourcesQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTraceSources>>> = ({ signal }) => getTraceSources(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getTraceSources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTraceSourcesQueryResult = NonNullable<Awaited<ReturnType<typeof getTraceSources>>>
export type GetTraceSourcesQueryError = ErrorModel



export function createGetTraceSources<TData = Awaited<ReturnType<typeof getTraceSources>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTraceSources>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetTraceSourcesQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type getTraceResponse200 = {
  data: GetTraceOutputBody
  status: 200
}

export type getTraceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getTraceResponseSuccess = (getTraceResponse200) & {
  headers: Headers;
};
export type getTraceResponseError = (getTraceResponseDefault) & {
  headers: Headers;
};

export type getTraceResponse = (getTraceResponseSuccess | getTraceResponseError)

export const getGetTraceUrl = (organizationId: string,
    traceId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/traces/${traceId}`
}

export const getTrace = async (organizationId: string,
    traceId: string, options?: RequestInit): Promise<getTraceResponse> => {
  
  const res = await fetch(getGetTraceUrl(organizationId,traceId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTraceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTraceResponse
}





export const getGetTraceQueryKey = (organizationId: string,
    traceId: string,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/traces/${traceId}`
    ] as const;
    }

    
export const getGetTraceQueryOptions = <TData = Awaited<ReturnType<typeof getTrace>>, TError = ErrorModel>(organizationId: string,
    traceId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTrace>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTraceQueryKey(organizationId,traceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrace>>> = ({ signal }) => getTrace(organizationId,traceId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId && traceId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getTrace>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTraceQueryResult = NonNullable<Awaited<ReturnType<typeof getTrace>>>
export type GetTraceQueryError = ErrorModel



export function createGetTrace<TData = Awaited<ReturnType<typeof getTrace>>, TError = ErrorModel>(
 organizationId: () =>  string,
    traceId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getTrace>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetTraceQueryOptions(organizationId(),
    traceId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




