/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  ErrorModel,
  GetMetricCatalogOutputBody,
  GetMetricCatalogParams,
  GetMetricSummaryOutputBody,
  GetMetricSummaryParams,
  GetREDMetricsOutputBody,
  GetRedMetricsParams,
  QueryTimeseriesOutputBody,
  QueryTimeseriesParams
} from '../../model';





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type getMetricCatalogResponse200 = {
  data: GetMetricCatalogOutputBody
  status: 200
}

export type getMetricCatalogResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getMetricCatalogResponseSuccess = (getMetricCatalogResponse200) & {
  headers: Headers;
};
export type getMetricCatalogResponseError = (getMetricCatalogResponseDefault) & {
  headers: Headers;
};

export type getMetricCatalogResponse = (getMetricCatalogResponseSuccess | getMetricCatalogResponseError)

export const getGetMetricCatalogUrl = (organizationId: string,
    params?: GetMetricCatalogParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations/${organizationId}/metrics/catalog?${stringifiedParams}` : `/api/v1/organizations/${organizationId}/metrics/catalog`
}

export const getMetricCatalog = async (organizationId: string,
    params?: GetMetricCatalogParams, options?: RequestInit): Promise<getMetricCatalogResponse> => {
  
  const res = await fetch(getGetMetricCatalogUrl(organizationId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMetricCatalogResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMetricCatalogResponse
}





export const getGetMetricCatalogQueryKey = (organizationId: string,
    params?: GetMetricCatalogParams,) => {
    return [
    `/api/v1/organizations/${organizationId}/metrics/catalog`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMetricCatalogQueryOptions = <TData = Awaited<ReturnType<typeof getMetricCatalog>>, TError = ErrorModel>(organizationId: string,
    params?: GetMetricCatalogParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getMetricCatalog>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetricCatalogQueryKey(organizationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetricCatalog>>> = ({ signal }) => getMetricCatalog(organizationId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getMetricCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetricCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getMetricCatalog>>>
export type GetMetricCatalogQueryError = ErrorModel



export function createGetMetricCatalog<TData = Awaited<ReturnType<typeof getMetricCatalog>>, TError = ErrorModel>(
 organizationId: () =>  string,
    params?: () =>  GetMetricCatalogParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getMetricCatalog>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetMetricCatalogQueryOptions(organizationId(),
    params?.(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type queryTimeseriesResponse200 = {
  data: QueryTimeseriesOutputBody
  status: 200
}

export type queryTimeseriesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type queryTimeseriesResponseSuccess = (queryTimeseriesResponse200) & {
  headers: Headers;
};
export type queryTimeseriesResponseError = (queryTimeseriesResponseDefault) & {
  headers: Headers;
};

export type queryTimeseriesResponse = (queryTimeseriesResponseSuccess | queryTimeseriesResponseError)

export const getQueryTimeseriesUrl = (organizationId: string,
    params: QueryTimeseriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations/${organizationId}/metrics/timeseries?${stringifiedParams}` : `/api/v1/organizations/${organizationId}/metrics/timeseries`
}

export const queryTimeseries = async (organizationId: string,
    params: QueryTimeseriesParams, options?: RequestInit): Promise<queryTimeseriesResponse> => {
  
  const res = await fetch(getQueryTimeseriesUrl(organizationId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: queryTimeseriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as queryTimeseriesResponse
}





export const getQueryTimeseriesQueryKey = (organizationId: string,
    params?: QueryTimeseriesParams,) => {
    return [
    `/api/v1/organizations/${organizationId}/metrics/timeseries`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getQueryTimeseriesQueryOptions = <TData = Awaited<ReturnType<typeof queryTimeseries>>, TError = ErrorModel>(organizationId: string,
    params: QueryTimeseriesParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof queryTimeseries>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getQueryTimeseriesQueryKey(organizationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof queryTimeseries>>> = ({ signal }) => queryTimeseries(organizationId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof queryTimeseries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type QueryTimeseriesQueryResult = NonNullable<Awaited<ReturnType<typeof queryTimeseries>>>
export type QueryTimeseriesQueryError = ErrorModel



export function createQueryTimeseries<TData = Awaited<ReturnType<typeof queryTimeseries>>, TError = ErrorModel>(
 organizationId: () =>  string,
    params: () =>  QueryTimeseriesParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof queryTimeseries>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getQueryTimeseriesQueryOptions(organizationId(),
    params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type getRedMetricsResponse200 = {
  data: GetREDMetricsOutputBody
  status: 200
}

export type getRedMetricsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getRedMetricsResponseSuccess = (getRedMetricsResponse200) & {
  headers: Headers;
};
export type getRedMetricsResponseError = (getRedMetricsResponseDefault) & {
  headers: Headers;
};

export type getRedMetricsResponse = (getRedMetricsResponseSuccess | getRedMetricsResponseError)

export const getGetRedMetricsUrl = (organizationId: string,
    params: GetRedMetricsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations/${organizationId}/metrics/red?${stringifiedParams}` : `/api/v1/organizations/${organizationId}/metrics/red`
}

export const getRedMetrics = async (organizationId: string,
    params: GetRedMetricsParams, options?: RequestInit): Promise<getRedMetricsResponse> => {
  
  const res = await fetch(getGetRedMetricsUrl(organizationId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getRedMetricsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRedMetricsResponse
}





export const getGetRedMetricsQueryKey = (organizationId: string,
    params?: GetRedMetricsParams,) => {
    return [
    `/api/v1/organizations/${organizationId}/metrics/red`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetRedMetricsQueryOptions = <TData = Awaited<ReturnType<typeof getRedMetrics>>, TError = ErrorModel>(organizationId: string,
    params: GetRedMetricsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getRedMetrics>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRedMetricsQueryKey(organizationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRedMetrics>>> = ({ signal }) => getRedMetrics(organizationId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getRedMetrics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRedMetricsQueryResult = NonNullable<Awaited<ReturnType<typeof getRedMetrics>>>
export type GetRedMetricsQueryError = ErrorModel



export function createGetRedMetrics<TData = Awaited<ReturnType<typeof getRedMetrics>>, TError = ErrorModel>(
 organizationId: () =>  string,
    params: () =>  GetRedMetricsParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getRedMetrics>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetRedMetricsQueryOptions(organizationId(),
    params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type getMetricSummaryResponse200 = {
  data: GetMetricSummaryOutputBody
  status: 200
}

export type getMetricSummaryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getMetricSummaryResponseSuccess = (getMetricSummaryResponse200) & {
  headers: Headers;
};
export type getMetricSummaryResponseError = (getMetricSummaryResponseDefault) & {
  headers: Headers;
};

export type getMetricSummaryResponse = (getMetricSummaryResponseSuccess | getMetricSummaryResponseError)

export const getGetMetricSummaryUrl = (organizationId: string,
    params: GetMetricSummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations/${organizationId}/metrics/summary?${stringifiedParams}` : `/api/v1/organizations/${organizationId}/metrics/summary`
}

export const getMetricSummary = async (organizationId: string,
    params: GetMetricSummaryParams, options?: RequestInit): Promise<getMetricSummaryResponse> => {
  
  const res = await fetch(getGetMetricSummaryUrl(organizationId,params),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMetricSummaryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMetricSummaryResponse
}





export const getGetMetricSummaryQueryKey = (organizationId: string,
    params?: GetMetricSummaryParams,) => {
    return [
    `/api/v1/organizations/${organizationId}/metrics/summary`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMetricSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getMetricSummary>>, TError = ErrorModel>(organizationId: string,
    params: GetMetricSummaryParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getMetricSummary>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMetricSummaryQueryKey(organizationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMetricSummary>>> = ({ signal }) => getMetricSummary(organizationId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getMetricSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMetricSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getMetricSummary>>>
export type GetMetricSummaryQueryError = ErrorModel



export function createGetMetricSummary<TData = Awaited<ReturnType<typeof getMetricSummary>>, TError = ErrorModel>(
 organizationId: () =>  string,
    params: () =>  GetMetricSummaryParams, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getMetricSummary>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetMetricSummaryQueryOptions(organizationId(),
    params(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




