// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organization_invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO organization_invitations (id, organization_id, email, role, invited_by_id, status, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'pending', $6, NOW(), NOW())
RETURNING id, organization_id, email, role, invited_by_id, status, expires_at, created_at, updated_at
`

type CreateInvitationParams struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	InvitedByID    string             `json:"invited_by_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.InvitedByID,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredInvitations = `-- name: DeleteExpiredInvitations :exec
DELETE FROM organization_invitations WHERE expires_at <= NOW() AND status = 'pending'
`

func (q *Queries) DeleteExpiredInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInvitations)
	return err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM organization_invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, organization_id, email, role, invited_by_id, status, expires_at, created_at, updated_at FROM organization_invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id string) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingInvitationByEmailAndOrg = `-- name: GetPendingInvitationByEmailAndOrg :one
SELECT id, organization_id, email, role, invited_by_id, status, expires_at, created_at, updated_at FROM organization_invitations
WHERE email = $1 AND organization_id = $2 AND status = 'pending' AND expires_at > NOW()
`

type GetPendingInvitationByEmailAndOrgParams struct {
	Email          string `json:"email"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetPendingInvitationByEmailAndOrg(ctx context.Context, arg GetPendingInvitationByEmailAndOrgParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByEmailAndOrg, arg.Email, arg.OrganizationID)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitationsByOrganizationID = `-- name: ListInvitationsByOrganizationID :many
SELECT 
    oi.id, oi.organization_id, oi.email, oi.role, oi.invited_by_id, oi.status, oi.expires_at, oi.created_at, oi.updated_at,
    u.name as inviter_name,
    u.email as inviter_email
FROM organization_invitations oi
JOIN users u ON oi.invited_by_id = u.id
WHERE oi.organization_id = $1
ORDER BY oi.created_at DESC
`

type ListInvitationsByOrganizationIDRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	InvitedByID    string             `json:"invited_by_id"`
	Status         string             `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	InviterName    string             `json:"inviter_name"`
	InviterEmail   string             `json:"inviter_email"`
}

func (q *Queries) ListInvitationsByOrganizationID(ctx context.Context, organizationID string) ([]ListInvitationsByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listInvitationsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsByOrganizationIDRow{}
	for rows.Next() {
		var i ListInvitationsByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.InvitedByID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InviterName,
			&i.InviterEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByEmail = `-- name: ListPendingInvitationsByEmail :many
SELECT 
    oi.id, oi.organization_id, oi.email, oi.role, oi.invited_by_id, oi.status, oi.expires_at, oi.created_at, oi.updated_at,
    o.name as org_name,
    o.slug as org_slug,
    u.name as inviter_name
FROM organization_invitations oi
JOIN organizations o ON oi.organization_id = o.id
JOIN users u ON oi.invited_by_id = u.id
WHERE oi.email = $1 AND oi.status = 'pending' AND oi.expires_at > NOW()
ORDER BY oi.created_at DESC
`

type ListPendingInvitationsByEmailRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	InvitedByID    string             `json:"invited_by_id"`
	Status         string             `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrgName        string             `json:"org_name"`
	OrgSlug        string             `json:"org_slug"`
	InviterName    string             `json:"inviter_name"`
}

func (q *Queries) ListPendingInvitationsByEmail(ctx context.Context, email string) ([]ListPendingInvitationsByEmailRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsByEmailRow{}
	for rows.Next() {
		var i ListPendingInvitationsByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.InvitedByID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgName,
			&i.OrgSlug,
			&i.InviterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE organization_invitations
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, email, role, invited_by_id, status, expires_at, created_at, updated_at
`

type UpdateInvitationStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, updateInvitationStatus, arg.ID, arg.Status)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.InvitedByID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
