// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organization_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMembersByOrganizationID = `-- name: CountMembersByOrganizationID :one
SELECT COUNT(*) FROM organization_members WHERE organization_id = $1
`

func (q *Queries) CountMembersByOrganizationID(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByOrganizationID, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_members (id, organization_id, user_id, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, organization_id, user_id, role, created_at, updated_at
`

type CreateOrganizationMemberParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
	Role           string `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM organization_members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const deleteMemberByOrgAndUser = `-- name: DeleteMemberByOrgAndUser :exec
DELETE FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type DeleteMemberByOrgAndUserParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) DeleteMemberByOrgAndUser(ctx context.Context, arg DeleteMemberByOrgAndUserParams) error {
	_, err := q.db.Exec(ctx, deleteMemberByOrgAndUser, arg.OrganizationID, arg.UserID)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, organization_id, user_id, role, created_at, updated_at FROM organization_members WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id string) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByOrgAndUser = `-- name: GetMemberByOrgAndUser :one
SELECT id, organization_id, user_id, role, created_at, updated_at FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetMemberByOrgAndUserParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetMemberByOrgAndUser(ctx context.Context, arg GetMemberByOrgAndUserParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getMemberByOrgAndUser, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOrganizationMemberships = `-- name: GetUserOrganizationMemberships :many
SELECT 
    om.id, om.organization_id, om.user_id, om.role, om.created_at, om.updated_at,
    o.name as org_name,
    o.slug as org_slug,
    o.logo as org_logo
FROM organization_members om
JOIN organizations o ON om.organization_id = o.id
WHERE om.user_id = $1
ORDER BY om.created_at DESC
`

type GetUserOrganizationMembershipsRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrgName        string             `json:"org_name"`
	OrgSlug        string             `json:"org_slug"`
	OrgLogo        pgtype.Text        `json:"org_logo"`
}

func (q *Queries) GetUserOrganizationMemberships(ctx context.Context, userID string) ([]GetUserOrganizationMembershipsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrganizationMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserOrganizationMembershipsRow{}
	for rows.Next() {
		var i GetUserOrganizationMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgName,
			&i.OrgSlug,
			&i.OrgLogo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByOrganizationID = `-- name: ListMembersByOrganizationID :many
SELECT 
    om.id, om.organization_id, om.user_id, om.role, om.created_at, om.updated_at,
    u.email,
    u.name,
    u.image
FROM organization_members om
JOIN users u ON om.user_id = u.id
WHERE om.organization_id = $1
ORDER BY om.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMembersByOrganizationIDParams struct {
	OrganizationID string `json:"organization_id"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type ListMembersByOrganizationIDRow struct {
	ID             string             `json:"id"`
	OrganizationID string             `json:"organization_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	Image          pgtype.Text        `json:"image"`
}

func (q *Queries) ListMembersByOrganizationID(ctx context.Context, arg ListMembersByOrganizationIDParams) ([]ListMembersByOrganizationIDRow, error) {
	rows, err := q.db.Query(ctx, listMembersByOrganizationID, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByOrganizationIDRow{}
	for rows.Next() {
		var i ListMembersByOrganizationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Name,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE organization_members
SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, user_id, role, created_at, updated_at
`

type UpdateMemberRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.ID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
