// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CheckSlugExists(ctx context.Context, slug string) (bool, error)
	CountMembersByOrganizationID(ctx context.Context, organizationID string) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id string) error
	DeleteExpiredInvitations(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteInvitation(ctx context.Context, id string) error
	DeleteMember(ctx context.Context, id string) error
	DeleteMemberByOrgAndUser(ctx context.Context, arg DeleteMemberByOrgAndUserParams) error
	DeleteOrganization(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionByToken(ctx context.Context, token string) error
	DeleteSessionsByUserID(ctx context.Context, userID string) error
	DeleteUser(ctx context.Context, id string) error
	GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) (Account, error)
	GetAccountsByUserID(ctx context.Context, userID string) ([]Account, error)
	GetInvitationByID(ctx context.Context, id string) (OrganizationInvitation, error)
	GetMemberByID(ctx context.Context, id string) (OrganizationMember, error)
	GetMemberByOrgAndUser(ctx context.Context, arg GetMemberByOrgAndUserParams) (OrganizationMember, error)
	GetOrganizationByID(ctx context.Context, id string) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPendingInvitationByEmailAndOrg(ctx context.Context, arg GetPendingInvitationByEmailAndOrgParams) (OrganizationInvitation, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error)
	GetSessionWithUserAndOrg(ctx context.Context, token string) (GetSessionWithUserAndOrgRow, error)
	GetSessionsByUserID(ctx context.Context, userID string) ([]Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserOrganizationMemberships(ctx context.Context, userID string) ([]GetUserOrganizationMembershipsRow, error)
	ListInvitationsByOrganizationID(ctx context.Context, organizationID string) ([]ListInvitationsByOrganizationIDRow, error)
	ListMembersByOrganizationID(ctx context.Context, arg ListMembersByOrganizationIDParams) ([]ListMembersByOrganizationIDRow, error)
	ListOrganizationsByUserID(ctx context.Context, userID string) ([]Organization, error)
	ListPendingInvitationsByEmail(ctx context.Context, email string) ([]ListPendingInvitationsByEmailRow, error)
	SetActiveOrganization(ctx context.Context, arg SetActiveOrganizationParams) (Session, error)
	UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error
	UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (OrganizationInvitation, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (OrganizationMember, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) (Session, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
