// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, token, user_id, active_organization_id, ip_address, user_agent, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, token, user_id, active_organization_id, ip_address, user_agent, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID                   string             `json:"id"`
	Token                string             `json:"token"`
	UserID               string             `json:"user_id"`
	ActiveOrganizationID pgtype.Text        `json:"active_organization_id"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.ActiveOrganizationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, token)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, token, user_id, active_organization_id, ip_address, user_agent, expires_at, created_at, updated_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, token, user_id, active_organization_id, ip_address, user_agent, expires_at, created_at, updated_at FROM sessions WHERE token = $1 AND expires_at > NOW()
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT 
    s.id as session_id,
    s.token,
    s.user_id,
    s.active_organization_id,
    s.ip_address,
    s.user_agent,
    s.expires_at,
    s.created_at as session_created_at,
    s.updated_at as session_updated_at,
    u.id as user_id,
    u.email,
    u.email_verified,
    u.name,
    u.image,
    u.created_at as user_created_at,
    u.updated_at as user_updated_at
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = $1 AND s.expires_at > NOW()
`

type GetSessionWithUserRow struct {
	SessionID            string             `json:"session_id"`
	Token                string             `json:"token"`
	UserID               string             `json:"user_id"`
	ActiveOrganizationID pgtype.Text        `json:"active_organization_id"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	SessionCreatedAt     pgtype.Timestamptz `json:"session_created_at"`
	SessionUpdatedAt     pgtype.Timestamptz `json:"session_updated_at"`
	UserID_2             string             `json:"user_id_2"`
	Email                string             `json:"email"`
	EmailVerified        bool               `json:"email_verified"`
	Name                 string             `json:"name"`
	Image                pgtype.Text        `json:"image"`
	UserCreatedAt        pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt        pgtype.Timestamptz `json:"user_updated_at"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, token)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.SessionCreatedAt,
		&i.SessionUpdatedAt,
		&i.UserID_2,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.Image,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getSessionWithUserAndOrg = `-- name: GetSessionWithUserAndOrg :one
SELECT 
    s.id as session_id,
    s.token,
    s.user_id,
    s.active_organization_id,
    s.ip_address,
    s.user_agent,
    s.expires_at,
    s.created_at as session_created_at,
    s.updated_at as session_updated_at,
    u.id as user_id,
    u.email,
    u.email_verified,
    u.name as user_name,
    u.image as user_image,
    u.created_at as user_created_at,
    u.updated_at as user_updated_at,
    o.id as org_id,
    o.name as org_name,
    o.slug as org_slug,
    o.logo as org_logo,
    o.metadata as org_metadata,
    o.created_at as org_created_at,
    om.role as member_role
FROM sessions s
JOIN users u ON s.user_id = u.id
LEFT JOIN organizations o ON s.active_organization_id = o.id
LEFT JOIN organization_members om ON o.id = om.organization_id AND u.id = om.user_id
WHERE s.token = $1 AND s.expires_at > NOW()
`

type GetSessionWithUserAndOrgRow struct {
	SessionID            string             `json:"session_id"`
	Token                string             `json:"token"`
	UserID               string             `json:"user_id"`
	ActiveOrganizationID pgtype.Text        `json:"active_organization_id"`
	IpAddress            pgtype.Text        `json:"ip_address"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	SessionCreatedAt     pgtype.Timestamptz `json:"session_created_at"`
	SessionUpdatedAt     pgtype.Timestamptz `json:"session_updated_at"`
	UserID_2             string             `json:"user_id_2"`
	Email                string             `json:"email"`
	EmailVerified        bool               `json:"email_verified"`
	UserName             string             `json:"user_name"`
	UserImage            pgtype.Text        `json:"user_image"`
	UserCreatedAt        pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt        pgtype.Timestamptz `json:"user_updated_at"`
	OrgID                pgtype.Text        `json:"org_id"`
	OrgName              pgtype.Text        `json:"org_name"`
	OrgSlug              pgtype.Text        `json:"org_slug"`
	OrgLogo              pgtype.Text        `json:"org_logo"`
	OrgMetadata          []byte             `json:"org_metadata"`
	OrgCreatedAt         pgtype.Timestamptz `json:"org_created_at"`
	MemberRole           pgtype.Text        `json:"member_role"`
}

func (q *Queries) GetSessionWithUserAndOrg(ctx context.Context, token string) (GetSessionWithUserAndOrgRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUserAndOrg, token)
	var i GetSessionWithUserAndOrgRow
	err := row.Scan(
		&i.SessionID,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.SessionCreatedAt,
		&i.SessionUpdatedAt,
		&i.UserID_2,
		&i.Email,
		&i.EmailVerified,
		&i.UserName,
		&i.UserImage,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.OrgID,
		&i.OrgName,
		&i.OrgSlug,
		&i.OrgLogo,
		&i.OrgMetadata,
		&i.OrgCreatedAt,
		&i.MemberRole,
	)
	return i, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, token, user_id, active_organization_id, ip_address, user_agent, expires_at, created_at, updated_at FROM sessions WHERE user_id = $1 AND expires_at > NOW()
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.UserID,
			&i.ActiveOrganizationID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveOrganization = `-- name: SetActiveOrganization :one
UPDATE sessions
SET active_organization_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, token, user_id, active_organization_id, ip_address, user_agent, expires_at, created_at, updated_at
`

type SetActiveOrganizationParams struct {
	ID                   string      `json:"id"`
	ActiveOrganizationID pgtype.Text `json:"active_organization_id"`
}

func (q *Queries) SetActiveOrganization(ctx context.Context, arg SetActiveOrganizationParams) (Session, error) {
	row := q.db.QueryRow(ctx, setActiveOrganization, arg.ID, arg.ActiveOrganizationID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionExpiry = `-- name: UpdateSessionExpiry :one
UPDATE sessions
SET expires_at = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, token, user_id, active_organization_id, ip_address, user_agent, expires_at, created_at, updated_at
`

type UpdateSessionExpiryParams struct {
	ID        string             `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionExpiry, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
