/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateApiKeyInputBody,
  CreateApiKeyOutputBody,
  ErrorModel,
  ListApiKeysOutputBody
} from '../../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type listApiKeysResponse200 = {
  data: ListApiKeysOutputBody
  status: 200
}

export type listApiKeysResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listApiKeysResponseSuccess = (listApiKeysResponse200) & {
  headers: Headers;
};
export type listApiKeysResponseError = (listApiKeysResponseDefault) & {
  headers: Headers;
};

export type listApiKeysResponse = (listApiKeysResponseSuccess | listApiKeysResponseError)

export const getListApiKeysUrl = (organizationId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/api-keys`
}

export const listApiKeys = async (organizationId: string, options?: RequestInit): Promise<listApiKeysResponse> => {
  
  const res = await fetch(getListApiKeysUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listApiKeysResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listApiKeysResponse
}





export const getListApiKeysQueryKey = (organizationId: string,) => {
    return [
    `/api/v1/organizations/${organizationId}/api-keys`
    ] as const;
    }

    
export const getListApiKeysQueryOptions = <TData = Awaited<ReturnType<typeof listApiKeys>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listApiKeys>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListApiKeysQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listApiKeys>>> = ({ signal }) => listApiKeys(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listApiKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof listApiKeys>>>
export type ListApiKeysQueryError = ErrorModel



export function createListApiKeys<TData = Awaited<ReturnType<typeof listApiKeys>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listApiKeys>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getListApiKeysQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type createApiKeyResponse200 = {
  data: CreateApiKeyOutputBody
  status: 200
}

export type createApiKeyResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createApiKeyResponseSuccess = (createApiKeyResponse200) & {
  headers: Headers;
};
export type createApiKeyResponseError = (createApiKeyResponseDefault) & {
  headers: Headers;
};

export type createApiKeyResponse = (createApiKeyResponseSuccess | createApiKeyResponseError)

export const getCreateApiKeyUrl = (organizationId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/api-keys`
}

export const createApiKey = async (organizationId: string,
    createApiKeyInputBody: NonReadonly<CreateApiKeyInputBody>, options?: RequestInit): Promise<createApiKeyResponse> => {
  
  const res = await fetch(getCreateApiKeyUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createApiKeyInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createApiKeyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createApiKeyResponse
}




export const getCreateApiKeyMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createApiKey>>, TError,{organizationId: string;data: NonReadonly<CreateApiKeyInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createApiKey>>, TError,{organizationId: string;data: NonReadonly<CreateApiKeyInputBody>}, TContext> => {

const mutationKey = ['createApiKey'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApiKey>>, {organizationId: string;data: NonReadonly<CreateApiKeyInputBody>}> = (props) => {
          const {organizationId,data} = props ?? {};

          return  createApiKey(organizationId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof createApiKey>>>
    export type CreateApiKeyMutationBody = NonReadonly<CreateApiKeyInputBody>
    export type CreateApiKeyMutationError = ErrorModel

    export const createCreateApiKey = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createApiKey>>, TError,{organizationId: string;data: NonReadonly<CreateApiKeyInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createApiKey>>,
        TError,
        {organizationId: string;data: NonReadonly<CreateApiKeyInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateApiKeyMutationOptions(options?.()), queryClient }));
    }
    export type revokeApiKeyResponse204 = {
  data: void
  status: 204
}

export type revokeApiKeyResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type revokeApiKeyResponseSuccess = (revokeApiKeyResponse204) & {
  headers: Headers;
};
export type revokeApiKeyResponseError = (revokeApiKeyResponseDefault) & {
  headers: Headers;
};

export type revokeApiKeyResponse = (revokeApiKeyResponseSuccess | revokeApiKeyResponseError)

export const getRevokeApiKeyUrl = (organizationId: string,
    keyId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/api-keys/${keyId}`
}

export const revokeApiKey = async (organizationId: string,
    keyId: string, options?: RequestInit): Promise<revokeApiKeyResponse> => {
  
  const res = await fetch(getRevokeApiKeyUrl(organizationId,keyId),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: revokeApiKeyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as revokeApiKeyResponse
}




export const getRevokeApiKeyMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof revokeApiKey>>, TError,{organizationId: string;keyId: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof revokeApiKey>>, TError,{organizationId: string;keyId: string}, TContext> => {

const mutationKey = ['revokeApiKey'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeApiKey>>, {organizationId: string;keyId: string}> = (props) => {
          const {organizationId,keyId} = props ?? {};

          return  revokeApiKey(organizationId,keyId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof revokeApiKey>>>
    
    export type RevokeApiKeyMutationError = ErrorModel

    export const createRevokeApiKey = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof revokeApiKey>>, TError,{organizationId: string;keyId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof revokeApiKey>>,
        TError,
        {organizationId: string;keyId: string},
        TContext
      > => {
      return createMutation(() => ({ ...getRevokeApiKeyMutationOptions(options?.()), queryClient }));
    }
    