/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateGithubInstallURLOutputBody,
  ErrorModel,
  ListGithubInstallationsOutputBody,
  ListGithubRepositoriesOutputBody,
  SetGithubRepositoryEnabledInputBody
} from '../../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type createGithubInstallUrlResponse200 = {
  data: CreateGithubInstallURLOutputBody
  status: 200
}

export type createGithubInstallUrlResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createGithubInstallUrlResponseSuccess = (createGithubInstallUrlResponse200) & {
  headers: Headers;
};
export type createGithubInstallUrlResponseError = (createGithubInstallUrlResponseDefault) & {
  headers: Headers;
};

export type createGithubInstallUrlResponse = (createGithubInstallUrlResponseSuccess | createGithubInstallUrlResponseError)

export const getCreateGithubInstallUrlUrl = (organizationId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/github/install-url`
}

export const createGithubInstallUrl = async (organizationId: string, options?: RequestInit): Promise<createGithubInstallUrlResponse> => {
  
  const res = await fetch(getCreateGithubInstallUrlUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createGithubInstallUrlResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createGithubInstallUrlResponse
}




export const getCreateGithubInstallUrlMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createGithubInstallUrl>>, TError,{organizationId: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createGithubInstallUrl>>, TError,{organizationId: string}, TContext> => {

const mutationKey = ['createGithubInstallUrl'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGithubInstallUrl>>, {organizationId: string}> = (props) => {
          const {organizationId} = props ?? {};

          return  createGithubInstallUrl(organizationId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGithubInstallUrlMutationResult = NonNullable<Awaited<ReturnType<typeof createGithubInstallUrl>>>
    
    export type CreateGithubInstallUrlMutationError = ErrorModel

    export const createCreateGithubInstallUrl = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createGithubInstallUrl>>, TError,{organizationId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createGithubInstallUrl>>,
        TError,
        {organizationId: string},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateGithubInstallUrlMutationOptions(options?.()), queryClient }));
    }
    export type listGithubInstallationsResponse200 = {
  data: ListGithubInstallationsOutputBody
  status: 200
}

export type listGithubInstallationsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listGithubInstallationsResponseSuccess = (listGithubInstallationsResponse200) & {
  headers: Headers;
};
export type listGithubInstallationsResponseError = (listGithubInstallationsResponseDefault) & {
  headers: Headers;
};

export type listGithubInstallationsResponse = (listGithubInstallationsResponseSuccess | listGithubInstallationsResponseError)

export const getListGithubInstallationsUrl = (organizationId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/github/installations`
}

export const listGithubInstallations = async (organizationId: string, options?: RequestInit): Promise<listGithubInstallationsResponse> => {
  
  const res = await fetch(getListGithubInstallationsUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listGithubInstallationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listGithubInstallationsResponse
}





export const getListGithubInstallationsQueryKey = (organizationId: string,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/github/installations`
    ] as const;
    }

    
export const getListGithubInstallationsQueryOptions = <TData = Awaited<ReturnType<typeof listGithubInstallations>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listGithubInstallations>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGithubInstallationsQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGithubInstallations>>> = ({ signal }) => listGithubInstallations(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listGithubInstallations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGithubInstallationsQueryResult = NonNullable<Awaited<ReturnType<typeof listGithubInstallations>>>
export type ListGithubInstallationsQueryError = ErrorModel



export function createListGithubInstallations<TData = Awaited<ReturnType<typeof listGithubInstallations>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listGithubInstallations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getListGithubInstallationsQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type listGithubRepositoriesResponse200 = {
  data: ListGithubRepositoriesOutputBody
  status: 200
}

export type listGithubRepositoriesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listGithubRepositoriesResponseSuccess = (listGithubRepositoriesResponse200) & {
  headers: Headers;
};
export type listGithubRepositoriesResponseError = (listGithubRepositoriesResponseDefault) & {
  headers: Headers;
};

export type listGithubRepositoriesResponse = (listGithubRepositoriesResponseSuccess | listGithubRepositoriesResponseError)

export const getListGithubRepositoriesUrl = (organizationId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/github/repositories`
}

export const listGithubRepositories = async (organizationId: string, options?: RequestInit): Promise<listGithubRepositoriesResponse> => {
  
  const res = await fetch(getListGithubRepositoriesUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listGithubRepositoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listGithubRepositoriesResponse
}





export const getListGithubRepositoriesQueryKey = (organizationId: string,) => {
    return [
    `http://localhost:8080/api/v1/organizations/${organizationId}/github/repositories`
    ] as const;
    }

    
export const getListGithubRepositoriesQueryOptions = <TData = Awaited<ReturnType<typeof listGithubRepositories>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listGithubRepositories>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGithubRepositoriesQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGithubRepositories>>> = ({ signal }) => listGithubRepositories(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listGithubRepositories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGithubRepositoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listGithubRepositories>>>
export type ListGithubRepositoriesQueryError = ErrorModel



export function createListGithubRepositories<TData = Awaited<ReturnType<typeof listGithubRepositories>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listGithubRepositories>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getListGithubRepositoriesQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type setGithubRepositoryEnabledResponse204 = {
  data: void
  status: 204
}

export type setGithubRepositoryEnabledResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type setGithubRepositoryEnabledResponseSuccess = (setGithubRepositoryEnabledResponse204) & {
  headers: Headers;
};
export type setGithubRepositoryEnabledResponseError = (setGithubRepositoryEnabledResponseDefault) & {
  headers: Headers;
};

export type setGithubRepositoryEnabledResponse = (setGithubRepositoryEnabledResponseSuccess | setGithubRepositoryEnabledResponseError)

export const getSetGithubRepositoryEnabledUrl = (organizationId: string,
    repositoryId: string,) => {


  

  return `http://localhost:8080/api/v1/organizations/${organizationId}/github/repositories/${repositoryId}`
}

export const setGithubRepositoryEnabled = async (organizationId: string,
    repositoryId: string,
    setGithubRepositoryEnabledInputBody: NonReadonly<SetGithubRepositoryEnabledInputBody>, options?: RequestInit): Promise<setGithubRepositoryEnabledResponse> => {
  
  const res = await fetch(getSetGithubRepositoryEnabledUrl(organizationId,repositoryId),
  {
      credentials: 'include',
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setGithubRepositoryEnabledInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: setGithubRepositoryEnabledResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as setGithubRepositoryEnabledResponse
}




export const getSetGithubRepositoryEnabledMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof setGithubRepositoryEnabled>>, TError,{organizationId: string;repositoryId: string;data: NonReadonly<SetGithubRepositoryEnabledInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof setGithubRepositoryEnabled>>, TError,{organizationId: string;repositoryId: string;data: NonReadonly<SetGithubRepositoryEnabledInputBody>}, TContext> => {

const mutationKey = ['setGithubRepositoryEnabled'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setGithubRepositoryEnabled>>, {organizationId: string;repositoryId: string;data: NonReadonly<SetGithubRepositoryEnabledInputBody>}> = (props) => {
          const {organizationId,repositoryId,data} = props ?? {};

          return  setGithubRepositoryEnabled(organizationId,repositoryId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SetGithubRepositoryEnabledMutationResult = NonNullable<Awaited<ReturnType<typeof setGithubRepositoryEnabled>>>
    export type SetGithubRepositoryEnabledMutationBody = NonReadonly<SetGithubRepositoryEnabledInputBody>
    export type SetGithubRepositoryEnabledMutationError = ErrorModel

    export const createSetGithubRepositoryEnabled = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof setGithubRepositoryEnabled>>, TError,{organizationId: string;repositoryId: string;data: NonReadonly<SetGithubRepositoryEnabledInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof setGithubRepositoryEnabled>>,
        TError,
        {organizationId: string;repositoryId: string;data: NonReadonly<SetGithubRepositoryEnabledInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getSetGithubRepositoryEnabledMutationOptions(options?.()), queryClient }));
    }
    