/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  CreateOrganizationInputBody,
  CreateOrganizationOutputBody,
  ErrorModel,
  GetSessionOutputBody,
  LoginInputBody,
  RegisterInputBody,
  SetActiveOrganizationInputBody
} from '../../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type loginResponse204 = {
  data: void
  status: 204
}

export type loginResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type loginResponseSuccess = (loginResponse204) & {
  headers: Headers;
};
export type loginResponseError = (loginResponseDefault) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {


  

  return `/api/v1/auth/login`
}

export const login = async (loginInputBody: NonReadonly<LoginInputBody>, options?: RequestInit): Promise<loginResponse> => {
  
  const res = await fetch(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}




export const getLoginMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: NonReadonly<LoginInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: NonReadonly<LoginInputBody>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: NonReadonly<LoginInputBody>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = NonReadonly<LoginInputBody>
    export type LoginMutationError = ErrorModel

    export const createLogin = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: NonReadonly<LoginInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: NonReadonly<LoginInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getLoginMutationOptions(options?.()), queryClient }));
    }
    export type logoutResponse204 = {
  data: void
  status: 204
}

export type logoutResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type logoutResponseSuccess = (logoutResponse204) & {
  headers: Headers;
};
export type logoutResponseError = (logoutResponseDefault) & {
  headers: Headers;
};

export type logoutResponse = (logoutResponseSuccess | logoutResponseError)

export const getLogoutUrl = () => {


  

  return `/api/v1/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<logoutResponse> => {
  
  const res = await fetch(getLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: logoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as logoutResponse
}




export const getLogoutMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = ErrorModel

    export const createLogout = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {
      return createMutation(() => ({ ...getLogoutMutationOptions(options?.()), queryClient }));
    }
    export type registerResponse204 = {
  data: void
  status: 204
}

export type registerResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type registerResponseSuccess = (registerResponse204) & {
  headers: Headers;
};
export type registerResponseError = (registerResponseDefault) & {
  headers: Headers;
};

export type registerResponse = (registerResponseSuccess | registerResponseError)

export const getRegisterUrl = () => {


  

  return `/api/v1/auth/register`
}

export const register = async (registerInputBody: NonReadonly<RegisterInputBody>, options?: RequestInit): Promise<registerResponse> => {
  
  const res = await fetch(getRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerResponse
}




export const getRegisterMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: NonReadonly<RegisterInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: NonReadonly<RegisterInputBody>}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: NonReadonly<RegisterInputBody>}> = (props) => {
          const {data} = props ?? {};

          return  register(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = NonReadonly<RegisterInputBody>
    export type RegisterMutationError = ErrorModel

    export const createRegister = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: NonReadonly<RegisterInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: NonReadonly<RegisterInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getRegisterMutationOptions(options?.()), queryClient }));
    }
    export type getSessionResponse200 = {
  data: GetSessionOutputBody
  status: 200
}

export type getSessionResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getSessionResponseSuccess = (getSessionResponse200) & {
  headers: Headers;
};
export type getSessionResponseError = (getSessionResponseDefault) & {
  headers: Headers;
};

export type getSessionResponse = (getSessionResponseSuccess | getSessionResponseError)

export const getGetSessionUrl = () => {


  

  return `/api/v1/auth/session`
}

export const getSession = async ( options?: RequestInit): Promise<getSessionResponse> => {
  
  const res = await fetch(getGetSessionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSessionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSessionResponse
}





export const getGetSessionQueryKey = () => {
    return [
    `/api/v1/auth/session`
    ] as const;
    }

    
export const getGetSessionQueryOptions = <TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorModel>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) => getSession({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>
export type GetSessionQueryError = ErrorModel



export function createGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorModel>(
  options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetSessionQueryOptions(options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type setActiveOrganizationResponse204 = {
  data: void
  status: 204
}

export type setActiveOrganizationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type setActiveOrganizationResponseSuccess = (setActiveOrganizationResponse204) & {
  headers: Headers;
};
export type setActiveOrganizationResponseError = (setActiveOrganizationResponseDefault) & {
  headers: Headers;
};

export type setActiveOrganizationResponse = (setActiveOrganizationResponseSuccess | setActiveOrganizationResponseError)

export const getSetActiveOrganizationUrl = () => {


  

  return `/api/v1/auth/session/active-organization`
}

export const setActiveOrganization = async (setActiveOrganizationInputBody: NonReadonly<SetActiveOrganizationInputBody>, options?: RequestInit): Promise<setActiveOrganizationResponse> => {
  
  const res = await fetch(getSetActiveOrganizationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setActiveOrganizationInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: setActiveOrganizationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as setActiveOrganizationResponse
}




export const getSetActiveOrganizationMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,{data: NonReadonly<SetActiveOrganizationInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,{data: NonReadonly<SetActiveOrganizationInputBody>}, TContext> => {

const mutationKey = ['setActiveOrganization'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setActiveOrganization>>, {data: NonReadonly<SetActiveOrganizationInputBody>}> = (props) => {
          const {data} = props ?? {};

          return  setActiveOrganization(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SetActiveOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof setActiveOrganization>>>
    export type SetActiveOrganizationMutationBody = NonReadonly<SetActiveOrganizationInputBody>
    export type SetActiveOrganizationMutationError = ErrorModel

    export const createSetActiveOrganization = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,{data: NonReadonly<SetActiveOrganizationInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof setActiveOrganization>>,
        TError,
        {data: NonReadonly<SetActiveOrganizationInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getSetActiveOrganizationMutationOptions(options?.()), queryClient }));
    }
    export type createOrganizationResponse200 = {
  data: CreateOrganizationOutputBody
  status: 200
}

export type createOrganizationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type createOrganizationResponseSuccess = (createOrganizationResponse200) & {
  headers: Headers;
};
export type createOrganizationResponseError = (createOrganizationResponseDefault) & {
  headers: Headers;
};

export type createOrganizationResponse = (createOrganizationResponseSuccess | createOrganizationResponseError)

export const getCreateOrganizationUrl = () => {


  

  return `/api/v1/organizations`
}

export const createOrganization = async (createOrganizationInputBody: NonReadonly<CreateOrganizationInputBody>, options?: RequestInit): Promise<createOrganizationResponse> => {
  
  const res = await fetch(getCreateOrganizationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createOrganizationInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createOrganizationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createOrganizationResponse
}




export const getCreateOrganizationMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: NonReadonly<CreateOrganizationInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: NonReadonly<CreateOrganizationInputBody>}, TContext> => {

const mutationKey = ['createOrganization'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrganization>>, {data: NonReadonly<CreateOrganizationInputBody>}> = (props) => {
          const {data} = props ?? {};

          return  createOrganization(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof createOrganization>>>
    export type CreateOrganizationMutationBody = NonReadonly<CreateOrganizationInputBody>
    export type CreateOrganizationMutationError = ErrorModel

    export const createCreateOrganization = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: NonReadonly<CreateOrganizationInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof createOrganization>>,
        TError,
        {data: NonReadonly<CreateOrganizationInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getCreateOrganizationMutationOptions(options?.()), queryClient }));
    }
    