/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orvo API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  AutoResolvePreview,
  AutoResolveThreshold,
  ErrorModel,
  ListAutoResolveThresholdsOutputBody,
  ListServiceRemediationMappingsOutputBody,
  RunLogAutoResolveOutputBody,
  ServiceRemediationMapping,
  UpsertAutoResolveThresholdInputBody,
  UpsertServiceRemediationMappingInputBody
} from '../../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type runLogAutoResolveResponse200 = {
  data: RunLogAutoResolveOutputBody
  status: 200
}

export type runLogAutoResolveResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type runLogAutoResolveResponseSuccess = (runLogAutoResolveResponse200) & {
  headers: Headers;
};
export type runLogAutoResolveResponseError = (runLogAutoResolveResponseDefault) & {
  headers: Headers;
};

export type runLogAutoResolveResponse = (runLogAutoResolveResponseSuccess | runLogAutoResolveResponseError)

export const getRunLogAutoResolveUrl = (organizationId: string,
    logId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/logs/${logId}/auto-resolve`
}

export const runLogAutoResolve = async (organizationId: string,
    logId: string, options?: RequestInit): Promise<runLogAutoResolveResponse> => {
  
  const res = await fetch(getRunLogAutoResolveUrl(organizationId,logId),
  {
      credentials: 'include',
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: runLogAutoResolveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as runLogAutoResolveResponse
}




export const getRunLogAutoResolveMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof runLogAutoResolve>>, TError,{organizationId: string;logId: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof runLogAutoResolve>>, TError,{organizationId: string;logId: string}, TContext> => {

const mutationKey = ['runLogAutoResolve'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runLogAutoResolve>>, {organizationId: string;logId: string}> = (props) => {
          const {organizationId,logId} = props ?? {};

          return  runLogAutoResolve(organizationId,logId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RunLogAutoResolveMutationResult = NonNullable<Awaited<ReturnType<typeof runLogAutoResolve>>>
    
    export type RunLogAutoResolveMutationError = ErrorModel

    export const createRunLogAutoResolve = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof runLogAutoResolve>>, TError,{organizationId: string;logId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof runLogAutoResolve>>,
        TError,
        {organizationId: string;logId: string},
        TContext
      > => {
      return createMutation(() => ({ ...getRunLogAutoResolveMutationOptions(options?.()), queryClient }));
    }
    export type getLogAutoResolvePreviewResponse200 = {
  data: AutoResolvePreview
  status: 200
}

export type getLogAutoResolvePreviewResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type getLogAutoResolvePreviewResponseSuccess = (getLogAutoResolvePreviewResponse200) & {
  headers: Headers;
};
export type getLogAutoResolvePreviewResponseError = (getLogAutoResolvePreviewResponseDefault) & {
  headers: Headers;
};

export type getLogAutoResolvePreviewResponse = (getLogAutoResolvePreviewResponseSuccess | getLogAutoResolvePreviewResponseError)

export const getGetLogAutoResolvePreviewUrl = (organizationId: string,
    logId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/logs/${logId}/auto-resolve/preview`
}

export const getLogAutoResolvePreview = async (organizationId: string,
    logId: string, options?: RequestInit): Promise<getLogAutoResolvePreviewResponse> => {
  
  const res = await fetch(getGetLogAutoResolvePreviewUrl(organizationId,logId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getLogAutoResolvePreviewResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getLogAutoResolvePreviewResponse
}





export const getGetLogAutoResolvePreviewQueryKey = (organizationId: string,
    logId: string,) => {
    return [
    `/api/v1/organizations/${organizationId}/logs/${logId}/auto-resolve/preview`
    ] as const;
    }

    
export const getGetLogAutoResolvePreviewQueryOptions = <TData = Awaited<ReturnType<typeof getLogAutoResolvePreview>>, TError = ErrorModel>(organizationId: string,
    logId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getLogAutoResolvePreview>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLogAutoResolvePreviewQueryKey(organizationId,logId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLogAutoResolvePreview>>> = ({ signal }) => getLogAutoResolvePreview(organizationId,logId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId && logId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getLogAutoResolvePreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLogAutoResolvePreviewQueryResult = NonNullable<Awaited<ReturnType<typeof getLogAutoResolvePreview>>>
export type GetLogAutoResolvePreviewQueryError = ErrorModel



export function createGetLogAutoResolvePreview<TData = Awaited<ReturnType<typeof getLogAutoResolvePreview>>, TError = ErrorModel>(
 organizationId: () =>  string,
    logId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getLogAutoResolvePreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getGetLogAutoResolvePreviewQueryOptions(organizationId(),
    logId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type listAutoResolveThresholdsResponse200 = {
  data: ListAutoResolveThresholdsOutputBody
  status: 200
}

export type listAutoResolveThresholdsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listAutoResolveThresholdsResponseSuccess = (listAutoResolveThresholdsResponse200) & {
  headers: Headers;
};
export type listAutoResolveThresholdsResponseError = (listAutoResolveThresholdsResponseDefault) & {
  headers: Headers;
};

export type listAutoResolveThresholdsResponse = (listAutoResolveThresholdsResponseSuccess | listAutoResolveThresholdsResponseError)

export const getListAutoResolveThresholdsUrl = (organizationId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/remediation/auto-resolve-thresholds`
}

export const listAutoResolveThresholds = async (organizationId: string, options?: RequestInit): Promise<listAutoResolveThresholdsResponse> => {
  
  const res = await fetch(getListAutoResolveThresholdsUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listAutoResolveThresholdsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listAutoResolveThresholdsResponse
}





export const getListAutoResolveThresholdsQueryKey = (organizationId: string,) => {
    return [
    `/api/v1/organizations/${organizationId}/remediation/auto-resolve-thresholds`
    ] as const;
    }

    
export const getListAutoResolveThresholdsQueryOptions = <TData = Awaited<ReturnType<typeof listAutoResolveThresholds>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listAutoResolveThresholds>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAutoResolveThresholdsQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAutoResolveThresholds>>> = ({ signal }) => listAutoResolveThresholds(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listAutoResolveThresholds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAutoResolveThresholdsQueryResult = NonNullable<Awaited<ReturnType<typeof listAutoResolveThresholds>>>
export type ListAutoResolveThresholdsQueryError = ErrorModel



export function createListAutoResolveThresholds<TData = Awaited<ReturnType<typeof listAutoResolveThresholds>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listAutoResolveThresholds>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getListAutoResolveThresholdsQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type deleteAutoResolveThresholdResponse204 = {
  data: void
  status: 204
}

export type deleteAutoResolveThresholdResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type deleteAutoResolveThresholdResponseSuccess = (deleteAutoResolveThresholdResponse204) & {
  headers: Headers;
};
export type deleteAutoResolveThresholdResponseError = (deleteAutoResolveThresholdResponseDefault) & {
  headers: Headers;
};

export type deleteAutoResolveThresholdResponse = (deleteAutoResolveThresholdResponseSuccess | deleteAutoResolveThresholdResponseError)

export const getDeleteAutoResolveThresholdUrl = (organizationId: string,
    serviceName: string,) => {


  

  return `/api/v1/organizations/${organizationId}/remediation/auto-resolve-thresholds/${serviceName}`
}

export const deleteAutoResolveThreshold = async (organizationId: string,
    serviceName: string, options?: RequestInit): Promise<deleteAutoResolveThresholdResponse> => {
  
  const res = await fetch(getDeleteAutoResolveThresholdUrl(organizationId,serviceName),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteAutoResolveThresholdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteAutoResolveThresholdResponse
}




export const getDeleteAutoResolveThresholdMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteAutoResolveThreshold>>, TError,{organizationId: string;serviceName: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteAutoResolveThreshold>>, TError,{organizationId: string;serviceName: string}, TContext> => {

const mutationKey = ['deleteAutoResolveThreshold'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAutoResolveThreshold>>, {organizationId: string;serviceName: string}> = (props) => {
          const {organizationId,serviceName} = props ?? {};

          return  deleteAutoResolveThreshold(organizationId,serviceName,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAutoResolveThresholdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAutoResolveThreshold>>>
    
    export type DeleteAutoResolveThresholdMutationError = ErrorModel

    export const createDeleteAutoResolveThreshold = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteAutoResolveThreshold>>, TError,{organizationId: string;serviceName: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteAutoResolveThreshold>>,
        TError,
        {organizationId: string;serviceName: string},
        TContext
      > => {
      return createMutation(() => ({ ...getDeleteAutoResolveThresholdMutationOptions(options?.()), queryClient }));
    }
    export type upsertAutoResolveThresholdResponse200 = {
  data: AutoResolveThreshold
  status: 200
}

export type upsertAutoResolveThresholdResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type upsertAutoResolveThresholdResponseSuccess = (upsertAutoResolveThresholdResponse200) & {
  headers: Headers;
};
export type upsertAutoResolveThresholdResponseError = (upsertAutoResolveThresholdResponseDefault) & {
  headers: Headers;
};

export type upsertAutoResolveThresholdResponse = (upsertAutoResolveThresholdResponseSuccess | upsertAutoResolveThresholdResponseError)

export const getUpsertAutoResolveThresholdUrl = (organizationId: string,
    serviceName: string,) => {


  

  return `/api/v1/organizations/${organizationId}/remediation/auto-resolve-thresholds/${serviceName}`
}

export const upsertAutoResolveThreshold = async (organizationId: string,
    serviceName: string,
    upsertAutoResolveThresholdInputBody: NonReadonly<UpsertAutoResolveThresholdInputBody>, options?: RequestInit): Promise<upsertAutoResolveThresholdResponse> => {
  
  const res = await fetch(getUpsertAutoResolveThresholdUrl(organizationId,serviceName),
  {
      credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertAutoResolveThresholdInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: upsertAutoResolveThresholdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as upsertAutoResolveThresholdResponse
}




export const getUpsertAutoResolveThresholdMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof upsertAutoResolveThreshold>>, TError,{organizationId: string;serviceName: string;data: NonReadonly<UpsertAutoResolveThresholdInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof upsertAutoResolveThreshold>>, TError,{organizationId: string;serviceName: string;data: NonReadonly<UpsertAutoResolveThresholdInputBody>}, TContext> => {

const mutationKey = ['upsertAutoResolveThreshold'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertAutoResolveThreshold>>, {organizationId: string;serviceName: string;data: NonReadonly<UpsertAutoResolveThresholdInputBody>}> = (props) => {
          const {organizationId,serviceName,data} = props ?? {};

          return  upsertAutoResolveThreshold(organizationId,serviceName,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertAutoResolveThresholdMutationResult = NonNullable<Awaited<ReturnType<typeof upsertAutoResolveThreshold>>>
    export type UpsertAutoResolveThresholdMutationBody = NonReadonly<UpsertAutoResolveThresholdInputBody>
    export type UpsertAutoResolveThresholdMutationError = ErrorModel

    export const createUpsertAutoResolveThreshold = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof upsertAutoResolveThreshold>>, TError,{organizationId: string;serviceName: string;data: NonReadonly<UpsertAutoResolveThresholdInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof upsertAutoResolveThreshold>>,
        TError,
        {organizationId: string;serviceName: string;data: NonReadonly<UpsertAutoResolveThresholdInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getUpsertAutoResolveThresholdMutationOptions(options?.()), queryClient }));
    }
    export type listServiceRemediationMappingsResponse200 = {
  data: ListServiceRemediationMappingsOutputBody
  status: 200
}

export type listServiceRemediationMappingsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type listServiceRemediationMappingsResponseSuccess = (listServiceRemediationMappingsResponse200) & {
  headers: Headers;
};
export type listServiceRemediationMappingsResponseError = (listServiceRemediationMappingsResponseDefault) & {
  headers: Headers;
};

export type listServiceRemediationMappingsResponse = (listServiceRemediationMappingsResponseSuccess | listServiceRemediationMappingsResponseError)

export const getListServiceRemediationMappingsUrl = (organizationId: string,) => {


  

  return `/api/v1/organizations/${organizationId}/remediation/service-mappings`
}

export const listServiceRemediationMappings = async (organizationId: string, options?: RequestInit): Promise<listServiceRemediationMappingsResponse> => {
  
  const res = await fetch(getListServiceRemediationMappingsUrl(organizationId),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listServiceRemediationMappingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listServiceRemediationMappingsResponse
}





export const getListServiceRemediationMappingsQueryKey = (organizationId: string,) => {
    return [
    `/api/v1/organizations/${organizationId}/remediation/service-mappings`
    ] as const;
    }

    
export const getListServiceRemediationMappingsQueryOptions = <TData = Awaited<ReturnType<typeof listServiceRemediationMappings>>, TError = ErrorModel>(organizationId: string, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listServiceRemediationMappings>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListServiceRemediationMappingsQueryKey(organizationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listServiceRemediationMappings>>> = ({ signal }) => listServiceRemediationMappings(organizationId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId), ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof listServiceRemediationMappings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListServiceRemediationMappingsQueryResult = NonNullable<Awaited<ReturnType<typeof listServiceRemediationMappings>>>
export type ListServiceRemediationMappingsQueryError = ErrorModel



export function createListServiceRemediationMappings<TData = Awaited<ReturnType<typeof listServiceRemediationMappings>>, TError = ErrorModel>(
 organizationId: () =>  string, options?: () => { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof listServiceRemediationMappings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: () => QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  

  const query = createQuery(() => getListServiceRemediationMappingsQueryOptions(organizationId(),options?.()), queryClient) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return query
}




export type deleteServiceRemediationMappingResponse204 = {
  data: void
  status: 204
}

export type deleteServiceRemediationMappingResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}
    
export type deleteServiceRemediationMappingResponseSuccess = (deleteServiceRemediationMappingResponse204) & {
  headers: Headers;
};
export type deleteServiceRemediationMappingResponseError = (deleteServiceRemediationMappingResponseDefault) & {
  headers: Headers;
};

export type deleteServiceRemediationMappingResponse = (deleteServiceRemediationMappingResponseSuccess | deleteServiceRemediationMappingResponseError)

export const getDeleteServiceRemediationMappingUrl = (organizationId: string,
    serviceName: string,) => {


  

  return `/api/v1/organizations/${organizationId}/remediation/service-mappings/${serviceName}`
}

export const deleteServiceRemediationMapping = async (organizationId: string,
    serviceName: string, options?: RequestInit): Promise<deleteServiceRemediationMappingResponse> => {
  
  const res = await fetch(getDeleteServiceRemediationMappingUrl(organizationId,serviceName),
  {
      credentials: 'include',
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteServiceRemediationMappingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteServiceRemediationMappingResponse
}




export const getDeleteServiceRemediationMappingMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteServiceRemediationMapping>>, TError,{organizationId: string;serviceName: string}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof deleteServiceRemediationMapping>>, TError,{organizationId: string;serviceName: string}, TContext> => {

const mutationKey = ['deleteServiceRemediationMapping'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteServiceRemediationMapping>>, {organizationId: string;serviceName: string}> = (props) => {
          const {organizationId,serviceName} = props ?? {};

          return  deleteServiceRemediationMapping(organizationId,serviceName,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteServiceRemediationMappingMutationResult = NonNullable<Awaited<ReturnType<typeof deleteServiceRemediationMapping>>>
    
    export type DeleteServiceRemediationMappingMutationError = ErrorModel

    export const createDeleteServiceRemediationMapping = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteServiceRemediationMapping>>, TError,{organizationId: string;serviceName: string}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteServiceRemediationMapping>>,
        TError,
        {organizationId: string;serviceName: string},
        TContext
      > => {
      return createMutation(() => ({ ...getDeleteServiceRemediationMappingMutationOptions(options?.()), queryClient }));
    }
    export type upsertServiceRemediationMappingResponse200 = {
  data: ServiceRemediationMapping
  status: 200
}

export type upsertServiceRemediationMappingResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}
    
export type upsertServiceRemediationMappingResponseSuccess = (upsertServiceRemediationMappingResponse200) & {
  headers: Headers;
};
export type upsertServiceRemediationMappingResponseError = (upsertServiceRemediationMappingResponseDefault) & {
  headers: Headers;
};

export type upsertServiceRemediationMappingResponse = (upsertServiceRemediationMappingResponseSuccess | upsertServiceRemediationMappingResponseError)

export const getUpsertServiceRemediationMappingUrl = (organizationId: string,
    serviceName: string,) => {


  

  return `/api/v1/organizations/${organizationId}/remediation/service-mappings/${serviceName}`
}

export const upsertServiceRemediationMapping = async (organizationId: string,
    serviceName: string,
    upsertServiceRemediationMappingInputBody: NonReadonly<UpsertServiceRemediationMappingInputBody>, options?: RequestInit): Promise<upsertServiceRemediationMappingResponse> => {
  
  const res = await fetch(getUpsertServiceRemediationMappingUrl(organizationId,serviceName),
  {
      credentials: 'include',
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertServiceRemediationMappingInputBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: upsertServiceRemediationMappingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as upsertServiceRemediationMappingResponse
}




export const getUpsertServiceRemediationMappingMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof upsertServiceRemediationMapping>>, TError,{organizationId: string;serviceName: string;data: NonReadonly<UpsertServiceRemediationMappingInputBody>}, TContext>, fetch?: RequestInit}
): CreateMutationOptions<Awaited<ReturnType<typeof upsertServiceRemediationMapping>>, TError,{organizationId: string;serviceName: string;data: NonReadonly<UpsertServiceRemediationMappingInputBody>}, TContext> => {

const mutationKey = ['upsertServiceRemediationMapping'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertServiceRemediationMapping>>, {organizationId: string;serviceName: string;data: NonReadonly<UpsertServiceRemediationMappingInputBody>}> = (props) => {
          const {organizationId,serviceName,data} = props ?? {};

          return  upsertServiceRemediationMapping(organizationId,serviceName,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpsertServiceRemediationMappingMutationResult = NonNullable<Awaited<ReturnType<typeof upsertServiceRemediationMapping>>>
    export type UpsertServiceRemediationMappingMutationBody = NonReadonly<UpsertServiceRemediationMappingInputBody>
    export type UpsertServiceRemediationMappingMutationError = ErrorModel

    export const createUpsertServiceRemediationMapping = <TError = ErrorModel,
    TContext = unknown>(options?: () => { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof upsertServiceRemediationMapping>>, TError,{organizationId: string;serviceName: string;data: NonReadonly<UpsertServiceRemediationMappingInputBody>}, TContext>, fetch?: RequestInit}
 , queryClient?: () => QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof upsertServiceRemediationMapping>>,
        TError,
        {organizationId: string;serviceName: string;data: NonReadonly<UpsertServiceRemediationMappingInputBody>},
        TContext
      > => {
      return createMutation(() => ({ ...getUpsertServiceRemediationMappingMutationOptions(options?.()), queryClient }));
    }
    